-- ============================================================================
-- El enlace de acceso: como entra un candidato que nunca eligio una contrasena
-- ============================================================================
--
-- El portal entra con correo y contrasena. Eso vale para quien se registro por su cuenta,
-- y no vale para nadie mas.
--
-- Las convocatorias que llegan como carpeta de curriculums no pasan por el registro: el
-- cargador crea la cuenta en nombre del candidato, con un correo inventado a partir del
-- nombre del archivo (`@cv-convocatoria.local`, un dominio que no existe) y una contrasena
-- que el candidato nunca va a conocer. Hoy hay 250 cuentas asi. Ninguna puede entrar, y
-- tampoco hay forma de recuperar la contrasena porque esa pantalla no existe.
--
-- Sin esto, el aviso que se le manda al candidato lleva a una puerta cerrada: puede leer el
-- correo y no puede responder la evaluacion, ni ver su prueba, ni subir su entregable.
--
-- Un enlace de acceso resuelve las dos cosas a la vez: identifica a la persona y le abre la
-- sesion sin pedirle nada que no tenga.
--
--
-- POR QUE SE GUARDA EL HASH Y NO EL TOKEN
--
-- Este token vale exactamente lo mismo que una contrasena: quien lo tenga entra como ese
-- candidato y ve su curriculum y sus notas. Guardarlo en claro seria repetir con otro nombre
-- el error que `contrasena_hash` ya evita. Se guarda el SHA-256; el token de verdad existe
-- una sola vez, en el correo que sale, y no se puede recuperar despues.
--
--
-- POR QUE NO ES DE UN SOLO USO
--
-- Un enlace de un solo uso parece mas seguro y aqui romperia el flujo. La sesion que abre
-- dura dos horas (`minutos-token-candidato`), y el candidato tiene DIAS de plazo para
-- responder: vuelve al dia siguiente, hace clic en el mismo correo y se encontraria con que
-- su unico enlace ya se gasto, sin forma de pedir otro. Ademas, muchos clientes de correo
-- abren los enlaces solos para previsualizarlos, asi que el enlace se gastaria antes de que
-- la persona lo tocara.
--
-- Se puede usar tantas veces como haga falta hasta que vence. Lo que acota el riesgo es el
-- vencimiento, que es corto y configurable, y que se puede revocar poniendo `revocado_en`.

CREATE TABLE enlace_acceso (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    postulacion_id bigint NOT NULL REFERENCES postulacion(id),
    -- SHA-256 del token en hexadecimal: 64 caracteres.
    token_hash     text   NOT NULL UNIQUE,
    vence_en       timestamptz NOT NULL,
    -- La primera y la ultima vez que se uso. Sirven para saber si el candidato llego a
    -- entrar: un enlace mandado y nunca usado es un candidato al que hay que llamar.
    primer_uso_en  timestamptz,
    ultimo_uso_en  timestamptz,
    usos           integer NOT NULL DEFAULT 0,
    -- Se llena para invalidarlo antes de tiempo, sin borrar la fila.
    revocado_en    timestamptz,
    creado_en      timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE enlace_acceso IS
    'Enlaces que abren el portal sin contrasena. Se guarda el hash, nunca el token.';

-- Se busca siempre por el hash al canjear: es la consulta caliente.
CREATE UNIQUE INDEX enlace_acceso_token_idx ON enlace_acceso (token_hash);
-- Para responder «que enlaces vigentes tiene esta postulacion» al reenviar una invitacion.
CREATE INDEX enlace_acceso_postulacion_idx ON enlace_acceso (postulacion_id, vence_en);


-- ============================================================================
-- Cuanto dura un enlace
-- ============================================================================
--
-- Va como parametro por lo mismo que el plazo de la evaluacion: es un numero que se mueve
-- segun la convocatoria y Renaser tiene que poder cambiarlo sin que nadie recompile. Treinta
-- dias cubre con holgura el plazo de una evaluacion (catorce por defecto) mas el retraso
-- entre que se reabre la tanda y sale el correo.

INSERT INTO parametro (organizacion_id, codigo, valor, tipo, descripcion)
SELECT o.id, 'dias_enlace_acceso', '30', 'ENTERO',
       'Cuantos dias vale el enlace que abre el portal sin contrasena'
FROM organizacion o
ON CONFLICT (organizacion_id, codigo) DO NOTHING;
