-- Cada vacante puede elegir sus propios textos de correo (22/08/2026).
--
-- POR QUE
-- -------
-- `plantilla_correo` es UNA por organizacion y codigo: al cambiar el texto de
-- `PRUEBA_DISPONIBLE` para que el candidato de Administrador responda en el portal, cambiaba
-- tambien el de Arquitecto y el de Ingeniero Civil, donde la entrega va por WhatsApp a
-- proposito mientras la pantalla de entregables no este terminada. No habia forma de decir
-- «este texto solo para esta convocatoria» salvo publicar una version, mandar, y restaurar
-- la anterior — que es justo lo que se hizo a mano con los primeros veintidos correos y
-- funciono porque nadie mas se movio en esos minutos.
--
-- La vacante ya elige su plantilla de evaluacion y su version de prueba. Esto le da lo
-- tercero que le faltaba: sus textos.
--
-- COMO
-- ----
-- Una fila dice «para esta vacante, donde el sistema fuera a mandar el aviso X, manda la
-- plantilla Y». `aviso_codigo` es el codigo que la maquina de estados habria usado
-- (PRUEBA_DISPONIBLE, POSTULACION_AVANZA, POSTULACION_NO_CONTINUA...), asi que no hace falta
-- una lista blanca aparte: lo que se puede sustituir es exactamente lo que el sistema manda.
--
-- Sin fila, manda el de siempre. Nada cambia para las vacantes que no configuren nada.
CREATE TABLE plantilla_correo_vacante (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vacante_id      bigint NOT NULL REFERENCES vacante(id),
    aviso_codigo    text NOT NULL,
    plantilla_codigo text NOT NULL,
    creado_en       timestamptz NOT NULL DEFAULT now(),
    -- Un aviso solo puede tener un reemplazo por vacante: con dos, cual sale seria cuestion
    -- de suerte y el candidato recibiria uno u otro sin que nada lo explicara.
    UNIQUE (vacante_id, aviso_codigo),
    -- Sustituir un aviso por si mismo no es un reemplazo: es una fila que confunde a quien
    -- la lee y no hace nada.
    CHECK (aviso_codigo <> plantilla_codigo)
);

CREATE INDEX plantilla_correo_vacante_vacante_idx ON plantilla_correo_vacante (vacante_id);

-- NO hay clave foranea contra `plantilla_correo`: alli el codigo se repite por version
-- (UNIQUE es organizacion_id + codigo + version), asi que no hay a que apuntar. Que el
-- codigo exista y este activo se comprueba al configurarlo, en
-- ServicioVacantesPanelImpl.asignarPlantillaCorreo.

COMMENT ON TABLE plantilla_correo_vacante IS
    'Que texto de correo usa ESTA vacante en lugar del que el sistema mandaria por defecto.';
