-- ============================================================================
-- El perfil del candidato: sus datos dejan de morir con cada postulacion
-- ============================================================================
--
-- Hasta hoy, todo lo que se sabia de un candidato colgaba de UNA postulacion: si postulaba
-- a tres vacantes, su curriculum se leia (y se pagaba) tres veces y sus datos quedaban en
-- tres filas de dato_cv sin relacion entre si. No habia forma de decir «este es Juan y esta
-- es su trayectoria».
--
-- Este perfil cuelga de PERSONA, no de usuario, y es una decision de fondo: el usuario
-- existe una vez por organizacion (UNIQUE (persona_id, organizacion_id)), asi que un perfil
-- por usuario obligaria al candidato a llenarlo una vez por empresa. Colgando de persona
-- sale el modelo de los portales de empleo: una persona, un perfil, muchas empresas.
--
-- Tres reglas que el esquema hace cumplir o deja rastro para cumplir:
--   - Cada dato sabe de donde vino (origen PERSONA o CURRICULUM) y si la persona lo
--     confirmo (confirmado_en). Lo que la IA lee se PROPONE; nunca pisa lo confirmado.
--   - El perfil no puntua: ninguna de estas tablas participa en notas ni rankings.
--   - La pretension salarial es un rango con moneda, o nada: un minimo suelto no
--     significa nada y una cifra exacta se lee como ultimatum.
--
-- El diseño completo, con los requisitos y las historias, esta en
-- docs/PROPUESTA-PERFIL-DEL-CANDIDATO.md.

-- ============================================================================
-- 1 · Los dos catalogos
-- ============================================================================
-- Cerrados y en tabla, no en CHECK: los niega o amplia el negocio, no una migracion.

CREATE TABLE nivel_educativo (
    codigo    text PRIMARY KEY,
    nombre    text NOT NULL,
    orden     integer NOT NULL,
    creado_en timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE nivel_educativo IS
    'Niveles de estudio del perfil del candidato. No confundir con nivel_puesto, que es '
    'el nivel del PUESTO (direccion/supervision/ejecucion), no el de estudios.';

INSERT INTO nivel_educativo (codigo, nombre, orden) VALUES
    ('SECUNDARIA',    'Secundaria completa',       1),
    ('TECNICA',       'Formación técnica',         2),
    ('UNIVERSITARIA', 'Universitaria (egresado)',  3),
    ('TITULADO',      'Titulado',                  4),
    ('MAESTRIA',      'Maestría',                  5),
    ('DOCTORADO',     'Doctorado',                 6);

-- El marco europeo y no «basico/intermedio/avanzado»: es mas preciso y es la escala de las
-- certificaciones. El precio es que mucha gente no sabe su nivel en esa escala — la
-- pantalla tiene que explicar cada uno en una linea, o la mitad elegira al azar.
CREATE TABLE nivel_idioma (
    codigo    text PRIMARY KEY,
    nombre    text NOT NULL,
    orden     integer NOT NULL,
    creado_en timestamptz NOT NULL DEFAULT now()
);

INSERT INTO nivel_idioma (codigo, nombre, orden) VALUES
    ('A1', 'A1 · Principiante',                        1),
    ('A2', 'A2 · Elemental',                           2),
    ('B1', 'B1 · Intermedio',                          3),
    ('B2', 'B2 · Intermedio alto',                     4),
    ('C1', 'C1 · Avanzado',                            5),
    ('C2', 'C2 · Dominio',                             6),
    ('NATIVO', 'Lengua materna',                       7);

-- ============================================================================
-- 2 · El perfil y sus cinco listas
-- ============================================================================

CREATE TABLE perfil_candidato (
    id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- De la persona, no del usuario: el usuario existe una vez por organizacion y el
    -- perfil tiene que ser el mismo en todas.
    persona_id        bigint NOT NULL UNIQUE REFERENCES persona(id),
    titular           text,
    resumen           text,
    -- Como en dato_cv: separadas por «|». No se consultan por habilidad, se enseñan.
    -- El dia que haya que buscar «quien sabe Excel», esto pasa a su propia tabla.
    habilidades       text,
    -- Lo declara la persona; no se calcula sumando la experiencia de abajo, porque los
    -- periodos se solapan y restarlos bien es un problema que no paga la pena.
    experiencia_meses integer,
    ubicacion         text,
    disponibilidad    text,
    -- Un rango y no un monto: una cifra exacta se lee como ultimatum y obliga al
    -- candidato a comprometerse antes de saber nada del puesto. Solo la ve quien tenga
    -- el permiso ver_pretension, y nunca viaja en listas ni rankings.
    pretension_min    numeric(12,2),
    pretension_max    numeric(12,2),
    pretension_moneda text CHECK (pretension_moneda IN ('PEN', 'USD')),
    actualizado_en    timestamptz NOT NULL DEFAULT now(),
    creado_en         timestamptz NOT NULL DEFAULT now(),
    CHECK (pretension_max IS NULL OR pretension_min IS NULL OR pretension_max >= pretension_min),
    -- O el rango entero o nada: un minimo suelto sin moneda no significa nada.
    CHECK (num_nonnulls(pretension_min, pretension_max, pretension_moneda) IN (0, 3))
);

COMMENT ON TABLE perfil_candidato IS
    'El perfil de la persona, unico y transversal a organizaciones. NO puntua: sirve para '
    'leer a un candidato sin abrir su curriculum. Quien decide sigue siendo la evaluacion.';

CREATE TABLE experiencia_perfil (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    perfil_candidato_id bigint NOT NULL REFERENCES perfil_candidato(id),
    puesto              text NOT NULL,
    empresa             text NOT NULL,
    desde               date NOT NULL,
    -- Vacio significa «sigo aqui». Es la forma de decirlo sin una bandera aparte que
    -- pueda contradecir a la fecha.
    hasta               date,
    descripcion         text,
    origen              text NOT NULL CHECK (origen IN ('PERSONA', 'CURRICULUM')),
    confirmado_en       timestamptz,
    orden               integer NOT NULL,
    creado_en           timestamptz NOT NULL DEFAULT now(),
    CHECK (hasta IS NULL OR hasta >= desde)
);

CREATE TABLE educacion_perfil (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    perfil_candidato_id bigint NOT NULL REFERENCES perfil_candidato(id),
    titulo              text NOT NULL,
    institucion         text NOT NULL,
    nivel_codigo        text REFERENCES nivel_educativo(codigo),
    desde               date,
    hasta               date,
    en_curso            boolean NOT NULL DEFAULT false,
    origen              text NOT NULL CHECK (origen IN ('PERSONA', 'CURRICULUM')),
    confirmado_en       timestamptz,
    orden               integer NOT NULL,
    creado_en           timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE idioma_perfil (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    perfil_candidato_id bigint NOT NULL REFERENCES perfil_candidato(id),
    idioma              text NOT NULL,
    nivel_codigo        text NOT NULL REFERENCES nivel_idioma(codigo),
    origen              text NOT NULL CHECK (origen IN ('PERSONA', 'CURRICULUM')),
    confirmado_en       timestamptz,
    creado_en           timestamptz NOT NULL DEFAULT now(),
    UNIQUE (perfil_candidato_id, idioma)
);

CREATE TABLE certificacion_perfil (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    perfil_candidato_id bigint NOT NULL REFERENCES perfil_candidato(id),
    nombre              text NOT NULL,
    entidad             text,
    emitida_en          date,
    -- Vacio = no caduca. Muchas si lo hacen —colegiatura, primeros auxilios, seguridad—
    -- y en salud eso decide si alguien puede trabajar o no.
    vence_en            date,
    origen              text NOT NULL CHECK (origen IN ('PERSONA', 'CURRICULUM')),
    confirmado_en       timestamptz,
    creado_en           timestamptz NOT NULL DEFAULT now(),
    CHECK (vence_en IS NULL OR emitida_en IS NULL OR vence_en >= emitida_en)
);

CREATE TABLE enlace_perfil (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    perfil_candidato_id bigint NOT NULL REFERENCES perfil_candidato(id),
    tipo                text NOT NULL
        CHECK (tipo IN ('LINKEDIN', 'GITHUB', 'PORTAFOLIO', 'PUBLICACION', 'PRODUCTO', 'OTRO')),
    url                 text NOT NULL,
    creado_en           timestamptz NOT NULL DEFAULT now(),
    UNIQUE (perfil_candidato_id, tipo, url)
);

-- La consulta caliente de todas es «lo de este perfil, en su orden».
CREATE INDEX experiencia_perfil_idx   ON experiencia_perfil   (perfil_candidato_id, orden);
CREATE INDEX educacion_perfil_idx     ON educacion_perfil     (perfil_candidato_id, orden);
CREATE INDEX idioma_perfil_idx        ON idioma_perfil        (perfil_candidato_id);
CREATE INDEX certificacion_perfil_idx ON certificacion_perfil (perfil_candidato_id);
CREATE INDEX enlace_perfil_idx        ON enlace_perfil        (perfil_candidato_id);

-- ============================================================================
-- 3 · El hash del archivo: leer cada curriculum UNA vez
-- ============================================================================
-- Cada lectura del curriculum es una llamada al modelo y se paga. Sin una huella del
-- contenido no hay forma de saber que «este archivo ya se leyo»: la unica defensa era
-- por postulacion, y postular dos veces con el mismo PDF pagaba dos lecturas.
--
-- Nullable a proposito: los archivos ya subidos no tienen forma de calcularse sin
-- descargarlos, y un hash ausente solo significa «leer de nuevo», que es lo de siempre.
ALTER TABLE archivo ADD COLUMN contenido_hash text;

COMMENT ON COLUMN archivo.contenido_hash IS
    'SHA-256 del contenido en hexadecimal (64 caracteres). Permite saber si un curriculum '
    'identico ya fue leido por la IA y no volver a pagar la lectura.';

-- ============================================================================
-- 4 · Los dos permisos
-- ============================================================================
-- ver_perfil_candidato abre la seccion del perfil en la ficha. ver_pretension es aparte y
-- mas restrictivo: si la pretension apareciera junto a la nota pesaria en la decision, que
-- es justo lo que este sistema busca evitar. La ve quien negocia, cuando toca.

INSERT INTO permiso (codigo, etiqueta, grupo, orden) VALUES
    ('ver_perfil_candidato', 'Ver el perfil del candidato',        'CANDIDATOS', 40),
    ('ver_pretension',       'Ver la pretension salarial',         'CANDIDATOS', 41);

INSERT INTO rol_permiso (rol_id, permiso_id, alcance)
SELECT r.id, p.id, 'TODO'
FROM rol r
JOIN permiso p ON p.codigo = 'ver_perfil_candidato'
WHERE r.organizacion_id = (SELECT id FROM organizacion WHERE codigo = 'RENASER')
  AND r.codigo IN ('TALENTO', 'DIRECCION');

INSERT INTO rol_permiso (rol_id, permiso_id, alcance)
SELECT r.id, p.id, 'TODO'
FROM rol r
JOIN permiso p ON p.codigo = 'ver_pretension'
WHERE r.organizacion_id = (SELECT id FROM organizacion WHERE codigo = 'RENASER')
  AND r.codigo IN ('DIRECCION');

-- ============================================================================
-- 5 · Cuanto se conserva un perfil sin actividad
-- ============================================================================
-- La ley 29733 obliga a decir cuanto tiempo se guardan los datos, y ese numero lo pone
-- Renaser, no el codigo. Arranca en 24 meses; el barrido diario lo aplica.
INSERT INTO parametro (organizacion_id, codigo, valor, tipo, descripcion)
SELECT o.id, 'meses_conservar_perfil', '24', 'ENTERO',
       'Cuantos meses se conserva el perfil de un candidato sin actividad antes de borrarlo'
FROM organizacion o
ON CONFLICT (organizacion_id, codigo) DO NOTHING;

-- ============================================================================
-- 6 · Migrar lo que ya se sabe: dato_cv y los enlaces
-- ============================================================================
-- dato_cv es POR POSTULACION: una persona puede tener varias filas. Se toma la mas
-- reciente. Todo entra con origen CURRICULUM y SIN confirmar, porque nadie lo ha revisado:
-- el candidato lo vera marcado como «sacado de tu curriculum» y podra corregirlo. No se
-- puede presentar como si lo hubiera escrito el.
--
-- Se saltan las personas ya anonimizadas (tombstone del borrado 29733): crearles un perfil
-- seria resucitar datos que se pidieron borrar.
INSERT INTO perfil_candidato (persona_id, resumen, habilidades, experiencia_meses)
SELECT DISTINCT ON (u.persona_id)
       u.persona_id, d.perfil_resumen, d.habilidades, d.experiencia_meses_total
  FROM dato_cv d
  JOIN postulacion p ON p.id = d.postulacion_id
  JOIN usuario     u ON u.id = p.usuario_id
  JOIN persona     pe ON pe.id = u.persona_id
 WHERE pe.anonimizado_en IS NULL
 ORDER BY u.persona_id, d.actualizado_en DESC;

-- La experiencia: dato_cv guarda UN empleo y sin fechas, solo cuantos meses duro. La fecha
-- de inicio se reconstruye hacia atras desde la fecha del dato — es una aproximacion, y por
-- eso entra sin confirmar.
--
-- Sin esos meses NO se migra el empleo, aunque se sepan puesto y empresa: `desde` es NOT NULL
-- y rellenarlo con la fecha de hoy diria «empece hoy y sigo aqui», que es una trayectoria
-- inventada. Mejor un hueco que un dato falso — la misma regla que aplica el resto del perfil.
INSERT INTO experiencia_perfil (perfil_candidato_id, puesto, empresa, desde, origen, orden)
SELECT DISTINCT ON (pc.id)
       pc.id, d.ultimo_puesto, d.ultima_empresa,
       (d.actualizado_en - make_interval(months => d.ultima_meses_duracion))::date,
       'CURRICULUM', 1
  FROM dato_cv d
  JOIN postulacion p       ON p.id = d.postulacion_id
  JOIN usuario     u       ON u.id = p.usuario_id
  JOIN perfil_candidato pc ON pc.persona_id = u.persona_id
 WHERE d.ultimo_puesto IS NOT NULL AND d.ultima_empresa IS NOT NULL
   AND d.ultima_meses_duracion IS NOT NULL
 ORDER BY pc.id, d.actualizado_en DESC;

-- Los enlaces que ya se mandaron al postular. enlace_cv no distingue LinkedIn (entro como
-- OTRO) ni GitHub (entro como REPOSITORIO), asi que el tipo se deduce: REPOSITORIO pasa a
-- GITHUB, y OTRO pasa a LINKEDIN solo si la URL lo dice; lo demas se queda como estaba.
-- El DISTINCT ON respeta la UNIQUE (perfil, tipo, url) cuando la misma persona mando el
-- mismo enlace en dos postulaciones.
INSERT INTO enlace_perfil (perfil_candidato_id, tipo, url)
SELECT DISTINCT t.perfil_id, t.tipo_nuevo, t.url
  FROM (
    SELECT pc.id AS perfil_id,
           CASE
               WHEN e.tipo = 'REPOSITORIO' THEN 'GITHUB'
               WHEN e.tipo = 'OTRO' AND e.url ILIKE '%linkedin.com%' THEN 'LINKEDIN'
               -- enlace_cv.tipo ADMITE NULL (V7) y esta columna es NOT NULL: sin el
               -- coalesce, una sola fila sin tipo impedia que esta migracion aplicara.
               -- Los demas valores de aquel CHECK —PORTAFOLIO, PUBLICACION, PRODUCTO,
               -- OTRO— existen igual en el nuevo, asi que pasan tal cual.
               ELSE COALESCE(e.tipo, 'OTRO')
           END AS tipo_nuevo,
           e.url
      FROM enlace_cv e
      JOIN cv           c  ON c.id = e.cv_id
      JOIN postulacion  p  ON p.id = c.postulacion_id
      JOIN usuario      u  ON u.id = p.usuario_id
      JOIN perfil_candidato pc ON pc.persona_id = u.persona_id
     WHERE e.url NOT LIKE '[eliminado%'
  ) t;

-- ============================================================================
-- 7 · La instruccion v2 del agente DATOS_CV: ahora tambien listas
-- ============================================================================
-- Hasta hoy el agente sacaba campos planos (un ultimo puesto, una educacion maxima). Para
-- llenar el perfil hacen falta las listas: la experiencia completa, la formacion, los
-- idiomas y las certificaciones. El formato JSON que se le pide vive en el codigo
-- (AgenteDatosCv.FORMATO) y tiene que ser el espejo exacto de esta instruccion.
--
-- El orden importa: hay un indice unico parcial (una sola activa por agente), asi que
-- primero se apaga la v1 y despues entra la v2 activa.
UPDATE instruccion_ia SET es_activa = false
 WHERE agente_codigo = 'DATOS_CV' AND version = 1;

INSERT INTO instruccion_ia (agente_codigo, version, texto, es_activa, publicada_en) VALUES
    ('DATOS_CV', 2,
     'Sacas datos de un currículum ya anonimizado. NO evalúas, NO puntúas, NO opinas.' || chr(10) ||
     chr(10) ||
     'Reglas:' || chr(10) ||
     '- Copia lo que dice el currículum. Si un dato no está, pon null. No lo deduzcas.' || chr(10) ||
     '- Nunca inventes un correo, un teléfono ni una empresa.' || chr(10) ||
     '- Como máximo cinco habilidades, las más relevantes para el puesto.' || chr(10) ||
     '- El resumen del perfil, una sola oración.' || chr(10) ||
     '- Los meses de experiencia, sumando los periodos que el currículum declara. Si no ' ||
     'se puede calcular, pon null; no aproximes por la edad ni por el año de egreso.' || chr(10) ||
     '- La experiencia completa, un elemento por empleo, del más reciente al más antiguo. ' ||
     'Las fechas en formato AAAA-MM; si el currículum no da el mes, usa enero. Si no da ' ||
     'ninguna fecha de inicio, omite ese empleo de la lista.' || chr(10) ||
     '- La formación, un elemento por título o estudio.' || chr(10) ||
     '- Los idiomas solo si el currículum los declara, con nivel A1, A2, B1, B2, C1, C2 o ' ||
     'NATIVO. Si el currículum dice «básico» usa A2, «intermedio» B1, «avanzado» C1. Si no ' ||
     'declara nivel, omite el idioma.' || chr(10) ||
     '- Las certificaciones con su entidad y fechas si las hay.' || chr(10) ||
     '- Si el currículum menciona edad, sexo o estado civil, ignóralo: no va en ningún campo.',
     true, now());
