-- ============================================================================
-- La plataforma y sus empresas: el esquema deja de asumir una sola organización
-- ============================================================================
--
-- Hasta hoy el sistema entero daba por hecho que solo existe Renaser: el portal buscaba
-- la organización por el código 'RENASER' escrito en el código, el banco «global» eran
-- filas con organizacion_id vacío, y el equipo entraba por RENASER OS, que solo conoce
-- a Renaser. El cambio a plataforma tipo Indeed —cada empresa se registra, publica sus
-- vacantes y ve solo a sus candidatos— necesita que todo eso sea un dato y no un texto
-- quemado. El porqué de cada decisión está en docs/superpowers/specs/2026-08-25-*.md.


-- ============================================================================
-- 1 · Quién es la plataforma, y qué tiene cada empresa de propio
-- ============================================================================
--
-- es_plataforma reemplaza al literal 'RENASER' del código: la dueña de la plataforma es
-- la organización que lo tenga puesto, y el índice parcial garantiza que solo una puede.
--
-- Las cuatro banderas son el corazón de la pieza A: apagada = la empresa lee el
-- instrumento de la plataforma (cero duplicación, una mejora de Renaser llega sola a
-- todas); encendida = se le copió y es suyo. Son independientes entre sí porque los
-- pesos se calculan por dimensión y las dimensiones son un catálogo global: una empresa
-- puede tener pesos propios y seguir evaluando con el banco de Renaser.

ALTER TABLE organizacion
    ADD COLUMN es_plataforma                  boolean NOT NULL DEFAULT false,
    ADD COLUMN banco_propio                   boolean NOT NULL DEFAULT false,
    ADD COLUMN pesos_propios                  boolean NOT NULL DEFAULT false,
    ADD COLUMN plantillas_evaluacion_propias  boolean NOT NULL DEFAULT false,
    ADD COLUMN pruebas_puesto_propias         boolean NOT NULL DEFAULT false;

CREATE UNIQUE INDEX organizacion_una_sola_plataforma
    ON organizacion (es_plataforma) WHERE es_plataforma;

UPDATE organizacion SET es_plataforma = true WHERE codigo = 'RENASER';


-- ============================================================================
-- 2 · La identidad del equipo deja de depender de RENASER OS
-- ============================================================================
--
-- El CHECK usuario_una_sola_identidad decía «o contraseña o id de RENASER OS, nunca las
-- dos»: era la forma de distinguir candidato de equipo. Con RENASER OS dormido, el
-- equipo entero —Renaser incluida— entra con correo y contraseña, así que un usuario de
-- equipo puede tener contraseña Y conservar su id de RENASER OS para el día que la
-- integración despierte. La distinción pasa a ser explícita: es_equipo.
--
-- Sin ese discriminador, el login del panel autenticaría candidatos como equipo: los
-- candidatos también tienen correo y contraseña, y solo esta columna los separa.

ALTER TABLE usuario DROP CONSTRAINT usuario_una_sola_identidad;

ALTER TABLE usuario ADD COLUMN es_equipo boolean NOT NULL DEFAULT false;

-- Los usuarios de equipo que ya existen son exactamente los que entraron por RENASER OS.
UPDATE usuario SET es_equipo = true WHERE usuario_renaser_os_id IS NOT NULL;


-- ============================================================================
-- 3 · Las invitaciones: la única puerta de entrada al panel
-- ============================================================================
--
-- El panel no tiene registro público: las cuentas nacen solo por invitación. Renaser
-- invita al administrador de cada empresa; cada administrador invita a su gente.
--
-- El token sigue el patrón de enlace_acceso (V24): 32 bytes de azar, se guarda solo el
-- SHA-256 en hexadecimal, y el token de verdad existe una única vez, en el correo que
-- sale. No se reutiliza esa tabla porque cuelga de una postulación y esto cuelga de una
-- organización; y al revés que aquel enlace, este es de UN SOLO USO: canjearlo crea la
-- cuenta, y una cuenta no se crea dos veces (canjear exige aceptada_en IS NULL).

CREATE TABLE invitacion (
    id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organizacion_id         bigint NOT NULL REFERENCES organizacion(id),
    correo                  text NOT NULL,
    -- Los códigos de rol que recibirá la cuenta al nacer, separados por coma. Van como
    -- texto y no como FK porque los roles son de la organización invitada y la fila
    -- debe poder crearse antes de que nadie de esa organización exista.
    roles                   text NOT NULL,
    -- SHA-256 del token en hexadecimal: 64 caracteres.
    token_hash              text NOT NULL UNIQUE,
    vence_en                timestamptz NOT NULL,
    aceptada_en             timestamptz,
    -- Se llena para invalidarla antes de tiempo, sin borrar la fila.
    revocada_en             timestamptz,
    creada_por_usuario_id   bigint REFERENCES usuario(id),
    creado_en               timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE invitacion IS
    'Invitaciones al panel de empresas. Se guarda el hash, nunca el token. Un solo uso.';

-- Para listar las pendientes de una organización al reenviar o revocar.
CREATE INDEX invitacion_organizacion_idx ON invitacion (organizacion_id, creado_en);

-- Cuántos días vale una invitación. Parámetro y no constante por lo mismo que el enlace
-- de acceso: es un número que se mueve y Renaser lo cambia sin recompilar.
INSERT INTO parametro (organizacion_id, codigo, valor, tipo, descripcion)
SELECT o.id, 'dias_invitacion', '7', 'ENTERO',
       'Cuántos días vale una invitación al panel antes de caducar'
FROM organizacion o
ON CONFLICT (organizacion_id, codigo) DO NOTHING;

-- El correo de una invitación va a alguien que todavía NO tiene cuenta: usuario_id no
-- puede ser obligatorio en el registro de correos. Todos los demás avisos lo siguen
-- llenando; solo la invitación lo deja vacío.
ALTER TABLE correo_enviado ALTER COLUMN usuario_id DROP NOT NULL;


-- ============================================================================
-- 4 · El banco deja de tener filas «globales»: todo tiene dueño
-- ============================================================================
--
-- organizacion_id vacío significaba «biblioteca global de Renaser» (V10). Ese modelo
-- choca con el de las banderas: si NULL es visible para todas, cualquier organización
-- podía además EDITARLO —laVersionVisible dejaba mutar la biblioteca global desde
-- cualquier org—. Con las banderas, «compartido» ya no es una fila sin dueño sino leer
-- las filas de la plataforma, así que el NULL se normaliza y la guarda queda estricta.

UPDATE version_banco
   SET organizacion_id = (SELECT id FROM organizacion WHERE es_plataforma)
 WHERE organizacion_id IS NULL;

ALTER TABLE version_banco ALTER COLUMN organizacion_id SET NOT NULL;


-- ============================================================================
-- 5 · De qué versión salió cada copia
-- ============================================================================
--
-- Encender una bandera copia la última versión publicada de la plataforma. La copia
-- guarda de cuál salió: sin esto, al comparar el instrumento de una empresa con el de
-- la plataforma no habría forma de saber si divergieron o nacieron distintos.

ALTER TABLE version_banco
    ADD COLUMN copiada_de_version_id bigint REFERENCES version_banco(id);
ALTER TABLE version_pesos
    ADD COLUMN copiada_de_version_id bigint REFERENCES version_pesos(id);
ALTER TABLE plantilla_evaluacion
    ADD COLUMN copiada_de_version_id bigint REFERENCES plantilla_evaluacion(id);
ALTER TABLE plantilla_prueba
    ADD COLUMN copiada_de_version_id bigint REFERENCES plantilla_prueba(id);


-- ============================================================================
-- 6 · Los permisos nuevos
-- ============================================================================
--
-- personalizar_instrumentos: encender o apagar las banderas. Del ADMINISTRADOR de cada
-- empresa (la copia de roles del alta lo arrastra a las empresas nuevas).
--
-- administrar_plataforma: dar de alta empresas. SOLO del ADMINISTRADOR de la
-- plataforma: el alta de empresas es la operación de Renaser como dueña, no una función
-- del panel de cualquier empresa. La copia de roles del alta lo excluye a propósito.

INSERT INTO permiso (codigo, etiqueta, grupo, orden) VALUES
    ('personalizar_instrumentos', 'Personalizar los instrumentos de evaluación', 'CONFIGURACION', 12),
    ('administrar_plataforma',    'Dar de alta y administrar empresas',          'CONFIGURACION', 13);

INSERT INTO rol_permiso (rol_id, permiso_id, alcance)
SELECT r.id, p.id, 'TODO'
FROM rol r
JOIN permiso p ON p.codigo = 'personalizar_instrumentos'
WHERE r.codigo = 'ADMINISTRADOR';

INSERT INTO rol_permiso (rol_id, permiso_id, alcance)
SELECT r.id, p.id, 'TODO'
FROM rol r
JOIN permiso p ON p.codigo = 'administrar_plataforma'
WHERE r.codigo = 'ADMINISTRADOR'
  AND r.organizacion_id = (SELECT id FROM organizacion WHERE es_plataforma);


-- ============================================================================
-- 7 · El texto de la invitación
-- ============================================================================
--
-- Si la plantilla no existe, ServicioCorreo anota un error y sigue EN SILENCIO: la
-- invitación quedaría creada y el correo jamás saldría, que es la peor combinación.
-- Por eso se siembra aquí y no se deja para el panel.

INSERT INTO plantilla_correo (organizacion_id, codigo, version, asunto, cuerpo, es_activa)
SELECT o.id, 'INVITACION_EQUIPO', 1,
       'Te invitaron al panel de {{nombre_empresa}}',
       'Hola:' || E'\n\n'
           || 'Te invitaron a formar parte del equipo de {{nombre_empresa}} en la plataforma de selección de Renaser. '
           || 'Para activar tu cuenta, abre este enlace y elige tu contraseña:' || E'\n\n'
           || '{{enlace}}' || E'\n\n'
           || 'La invitación vence el {{vence}}. Si no esperabas este correo, ignóralo.' || E'\n\n'
           || 'Equipo de Talento · Renaser',
       true
FROM organizacion o
WHERE o.es_plataforma;
