-- ============================================================================
-- El candidato ante varias empresas, el coste de la IA y la dueña (piezas D/E/F)
-- ============================================================================
--
-- Segunda tanda del multiempresa. La fase 1 (V37) hizo que el esquema dejara de asumir
-- una sola organización; esta cierra lo que quedaba: el consentimiento que el candidato
-- firma con CADA empresa al postular, el precio de cada llamada al modelo con su tope
-- mensual, y el aviso de que una empresa se acerca a su tope. La suspensión de empresas
-- (pieza F) no necesita esquema: organizacion.es_activa existe desde la V2 — lo que
-- faltaba era comprobarla, y eso es código. El porqué de cada decisión está en
-- docs/superpowers/specs/2026-08-25-*.md.


-- ============================================================================
-- 1 · El consentimiento de PROCESO queda amarrado a su postulación (pieza D)
-- ============================================================================
--
-- Al crear la cuenta el candidato consiente con la PLATAFORMA (eso ya existía). Al
-- postular acepta el texto de ESA empresa, y el registro firmado queda a nombre de ella
-- y de esa postulación concreta: postular a tres empresas son tres filas, cada una con
-- su papel en regla (ley 29733: cada quien que trata datos, nombrado y consentido).

ALTER TABLE consentimiento
    ADD COLUMN postulacion_id bigint REFERENCES postulacion(id);

COMMENT ON COLUMN consentimiento.postulacion_id IS
    'La postulación que firmó este consentimiento. Vacío = consentimiento de cuenta con '
    'la plataforma (crear la cuenta, futuros contactos); lleno = el texto PROCESO de la '
    'empresa de esa vacante, aceptado al postular.';

-- El UNIQUE(persona_id, texto_consentimiento_id) impedía re-postular: quien postula dos
-- veces a la misma empresa con el mismo texto vigente firmaría dos veces la misma fila.
-- Se conserva SOLO para las filas de cuenta (postulacion_id vacío), donde sigue siendo
-- verdad que una persona no acepta dos veces el mismo texto; las filas de postulación
-- ya son únicas por otra vía (una postulación firma una sola vez su texto).
ALTER TABLE consentimiento
    DROP CONSTRAINT consentimiento_persona_id_texto_consentimiento_id_key;

CREATE UNIQUE INDEX consentimiento_de_cuenta_unico
    ON consentimiento (persona_id, texto_consentimiento_id)
    WHERE postulacion_id IS NULL;

CREATE UNIQUE INDEX consentimiento_de_postulacion_unico
    ON consentimiento (postulacion_id, texto_consentimiento_id)
    WHERE postulacion_id IS NOT NULL;


-- ============================================================================
-- 2 · La tarifa por modelo, con vigencia por fecha (pieza E)
-- ============================================================================
--
-- ejecucion_ia.costo existe desde la V11 y nunca se ha rellenado. Para rellenarlo hace
-- falta el precio, y el precio cambia: cuando el proveedor lo mueve se registra una
-- tarifa nueva y LO YA EJECUTADO CONSERVA la suya — sin vigencia, un cambio de precios
-- reescribiría el pasado.
--
-- Sin vigente_hasta a propósito: la vigente de (proveedor, modelo) es la de
-- vigente_desde más reciente que ya empezó. Así no hay huecos ni solapes que validar.

CREATE TABLE tarifa_modelo (
    id                        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proveedor                 text NOT NULL,
    modelo                    text NOT NULL,
    precio_entrada_por_millon numeric(10,4) NOT NULL,
    precio_salida_por_millon  numeric(10,4) NOT NULL,
    vigente_desde             timestamptz NOT NULL,
    creado_en                 timestamptz NOT NULL DEFAULT now(),
    UNIQUE (proveedor, modelo, vigente_desde)
);

COMMENT ON TABLE tarifa_modelo IS
    'Precio por millón de tokens de cada modelo, mantenido por Renaser. La vigente es la '
    'de vigente_desde más reciente <= ahora; una tarifa nueva no toca costos ya escritos.';

-- La búsqueda de cada cierre de ejecución: (proveedor, modelo) y la más reciente.
CREATE INDEX tarifa_modelo_vigencia_idx ON tarifa_modelo (proveedor, modelo, vigente_desde DESC);

-- Tarifas PROVISIONALES: ajustar con la factura real — el número exacto lo pone Renaser.
-- El proveedor va en minúsculas porque así lo escribe la bitácora (ClienteModeloDeepSeek
-- registra 'deepseek'); el cálculo compara sin distinguir mayúsculas por si acaso.
-- Valores de referencia de agosto 2026: DeepSeek ~$0.27/$1.10 por millón; el embedding
-- de Google ~$0.15 la entrada (no devuelve tokens de salida).
INSERT INTO tarifa_modelo (proveedor, modelo, precio_entrada_por_millon, precio_salida_por_millon, vigente_desde) VALUES
    ('deepseek', 'deepseek-v4-flash',  0.2700, 1.1000, now()),
    ('google',   'gemini-embedding-2', 0.1500, 0.0000, now());


-- ============================================================================
-- 3 · El trabajo que espera su cupo (pieza E)
-- ============================================================================
--
-- Al 100% del tope mensual, lo nuevo no falla: ESPERA. El candidato ve «en curso», que
-- es la verdad; cuando Renaser sube el tope o empieza el mes, el sondeo lo despierta.
-- El catálogo de estados es un CHECK y ampliarlo es soltarlo y volverlo a atar, igual
-- que hizo la V19 con el catálogo de agentes.

ALTER TABLE trabajo_ia DROP CONSTRAINT trabajo_ia_estado_check;
ALTER TABLE trabajo_ia ADD CONSTRAINT trabajo_ia_estado_check
    CHECK (estado IN ('PENDIENTE', 'EN_CURSO', 'TERMINADO', 'FALLIDO', 'EN_ESPERA'));

-- El sondeo que despierta busca por estado: mismo patrón que trabajo_ia_pendiente_idx.
CREATE INDEX trabajo_ia_en_espera_idx ON trabajo_ia (organizacion_id) WHERE estado = 'EN_ESPERA';

-- El consumo del mes se suma por organización y fechas cada vez que se encola un
-- trabajo de una empresa con tope; el índice por creado_en a secas obligaba a leer el
-- mes entero de TODAS las empresas.
CREATE INDEX ejecucion_ia_organizacion_creado_idx ON ejecucion_ia (organizacion_id, creado_en);


-- ============================================================================
-- 4 · El aviso del 80% (pieza E)
-- ============================================================================
--
-- Para TODAS las organizaciones y no solo la plataforma (patrón V24/V26): la que exista
-- hoy sin esta plantilla jamás avisaría — ServicioCorreo anota el error y sigue en
-- silencio. A las empresas nuevas se la copia el alta (copia las activas).

INSERT INTO plantilla_correo (organizacion_id, codigo, version, asunto, cuerpo, es_activa, creado_en)
SELECT o.id, 'TOPE_IA_AVISO', 1,
       'El consumo de IA de {{empresa}} va por el {{porcentaje}}% de su tope',
       'Hola:' || chr(10) || chr(10) ||
       'El consumo de inteligencia artificial de {{empresa}} en {{mes}} llegó a ' ||
       '{{consumo}} USD, el {{porcentaje}}% de su tope mensual de {{tope}} USD.' || chr(10) || chr(10) ||
       'Al llegar al 100% las calificaciones nuevas quedarán en espera —sin fallar y sin ' ||
       'frenar las postulaciones— hasta que suba el tope o empiece el mes siguiente.' || chr(10) || chr(10) ||
       'Equipo de Talento · Renaser',
       true, now()
FROM organizacion o
WHERE NOT EXISTS (
      SELECT 1 FROM plantilla_correo pc
       WHERE pc.organizacion_id = o.id AND pc.codigo = 'TOPE_IA_AVISO');
