-- La prueba técnica, ciclo 1: la ficha de vacante y el agente REDACTOR.
-- Ver docs/DISENO-PRUEBA-TECNICA-FICHA-Y-REDACTOR.md y docs/CAZATALENTOS-PRUEBA-TECNICA.md.
--
-- La etapa 2 del método CAZATALENTOS no es fija: el cuestionario no existe hasta que
-- existe la vacante, y se escribe para ella. El dueño llena una ficha (las 10 preguntas
-- de la clienta), un agente redacta el borrador siguiendo la receta mecánica del método,
-- y el dueño aprueba. El cuestionario aprobado ES un banco CRITERIOS ligado a la
-- vacante: cero motores nuevos — el portal, la calificación por criterios y la
-- recalificación que ya existen sirven tal cual.

-- ============================================================================
-- 1 · La ficha de vacante
-- ============================================================================
-- Una por vacante. Todo puede estar a medias mientras el dueño la piensa (BORRADOR);
-- qué la vuelve COMPLETA lo decide el servicio, no la base — por eso casi todo es NULL.
--
-- Los riesgos son columnas y no un párrafo: su ORDEN es la velocidad de daño, la decide
-- el dueño y después manda en el cuestionario. Las eliminatorias son dos porque el
-- método dice máximo 2; los requerimientos, tres por lo mismo (Q9). Q10 (el espejo) es
-- opcional: solo aplica si ya contrató antes para el puesto.
CREATE TABLE ficha_vacante (
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vacante_id       bigint NOT NULL UNIQUE REFERENCES vacante(id),
    organizacion_id  bigint NOT NULL REFERENCES organizacion(id),

    -- Las 10 respuestas del dueño, con sus palabras.
    q1_resultado     text,
    q2_riesgo        text,
    q3_dia_real      text,
    q4_epoca_dorada  text,
    q5_estructura    text,
    q6_autonomia     text,
    q7_jefe_directo  text,
    q8_lo_incomodo   text,
    q9_requerimientos text,
    q10_espejo       text,

    -- Lo estructurado que no se parsea de texto libre.
    gente_en_empresa integer CHECK (gente_en_empresa IS NULL OR gente_en_empresa >= 0),
    gente_a_cargo    integer CHECK (gente_a_cargo IS NULL OR gente_a_cargo >= 0),
    riesgo_1         text,
    riesgo_2         text,
    riesgo_3         text,
    riesgo_4         text,
    eliminatoria_1   text,
    eliminatoria_2   text,
    requerimiento_1  text,
    requerimiento_2  text,
    requerimiento_3  text,

    -- Salidas del método. La familia decide el diccionario de textura (ciclo 4); puede
    -- ser más de una, en orden de importancia: 'F4' o 'F4,F1'.
    familias         text CHECK (familias IS NULL OR familias ~ '^F[1-7](,F[1-7])*$'),
    -- Derivado de gente_en_empresa (≤30 MICRO · 31–200 MEDIA · 200+ GRANDE). Es la única
    -- dependencia de la etapa 2 hacia la 1: elige los pesos de pilar de DIRECCION.
    tamano           text CHECK (tamano IS NULL OR tamano IN ('MICRO', 'MEDIA', 'GRANDE')),

    estado           text NOT NULL DEFAULT 'BORRADOR'
        CHECK (estado IN ('BORRADOR', 'COMPLETA')),
    creado_en        timestamptz NOT NULL DEFAULT now(),
    -- Contra esto se computa «el cuestionario quedó desactualizado»: ficha más nueva
    -- que el borrador generado. Sin columna de bandera: la comparación no miente.
    actualizado_en   timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX ficha_vacante_organizacion_idx ON ficha_vacante (organizacion_id);

-- ============================================================================
-- 2 · El banco por vacante
-- ============================================================================
-- NULL = banco por nivel, como hasta hoy (v0.1, v3, CAZATALENTOS etapa 1). Con valor =
-- el cuestionario técnico de ESA vacante. La selección de banco para la etapa técnica
-- mira primero el de la vacante; publicar uno de vacante NO archiva los bancos por
-- nivel de la plataforma — son mundos distintos.
-- Y su propio tipo: un cuestionario de vacante no es un banco de nivel ni de alineación.
ALTER TABLE version_banco DROP CONSTRAINT version_banco_tipo_banco_check;
ALTER TABLE version_banco ADD CONSTRAINT version_banco_tipo_banco_check
    CHECK (tipo_banco IN ('NIVEL', 'ALINEACION', 'VACANTE'));

ALTER TABLE version_banco ADD COLUMN vacante_id bigint REFERENCES vacante(id);
COMMENT ON COLUMN version_banco.vacante_id IS
    'NULL = banco por nivel (plataforma) · con valor = cuestionario técnico de esa vacante';

-- Solo un borrador vivo y una publicada por vacante: regenerar archiva el borrador
-- anterior (nada se borra, RF-138) y crea el nuevo.
CREATE UNIQUE INDEX version_banco_borrador_por_vacante_idx
    ON version_banco (vacante_id) WHERE vacante_id IS NOT NULL AND estado = 'BORRADOR';
CREATE UNIQUE INDEX version_banco_publicada_por_vacante_idx
    ON version_banco (vacante_id) WHERE vacante_id IS NOT NULL AND estado = 'PUBLICADA';

-- La muestra de trabajo se genera y se guarda, pero JAMÁS se envía al candidato en el
-- formulario: regala el diagnóstico del negocio a todo el que postule. Se le enseña
-- solo al dueño, para su entrevista presencial.
ALTER TABLE pregunta ADD COLUMN presencial boolean NOT NULL DEFAULT false;

-- ============================================================================
-- 3 · El agente REDACTOR
-- ============================================================================
-- El agente número 11, y el único nuevo de todo el proyecto de la prueba técnica. No
-- puede llamarse CAZATALENTOS: ese código ya lo usa uno de los nueve originales (V11).
-- El catálogo es cerrado y la restricción los enumera, así que añadir uno pasa por
-- rehacerla (patrón de V19).
--
-- Regla vigente del sistema que este agente cumple al pie: un agente puede generar
-- texto que no entre en una nota. Sus preguntas no tocan a nadie hasta que un humano
-- las publica.
ALTER TABLE agente DROP CONSTRAINT agente_codigo_check;
ALTER TABLE agente ADD CONSTRAINT agente_codigo_check
    CHECK (codigo IN ('NECESIDAD_TALENTO', 'CAZATALENTOS', 'DATOS_CV', 'EVIDENCIA_CV',
                      'EVALUADOR', 'POTENCIAL_RIESGO', 'PRUEBA_PUESTO', 'SIMULACION',
                      'DESEMPENO', 'APRENDIZAJE', 'REDACTOR'));

INSERT INTO agente (codigo, nombre, descripcion, version, es_activo) VALUES
    ('REDACTOR', 'Redactor de la prueba técnica',
     'Convierte la ficha de vacante en el borrador del cuestionario técnico, siguiendo '
     'la receta del método: por riesgo, una de experiencia con magnitudes y una de '
     'procedimiento exacto. Solo propone: publica el dueño', 1, true);

-- Sin instrucción activa el ejecutor se niega a llamar al modelo, así que nace con ella.
-- La estructura exacta (bloques y cantidades del nivel) viaja en cada llamada como dato:
-- la instrucción es el oficio, no la receta.
INSERT INTO instruccion_ia (agente_codigo, version, texto, es_activa, publicada_en) VALUES
    ('REDACTOR', 1,
     'Redactas el cuestionario técnico de una vacante a partir de la ficha que llenó el ' ||
     'dueño del negocio. NO evalúas a nadie: escribes preguntas.' || chr(10) ||
     chr(10) ||
     'Reglas:' || chr(10) ||
     '- La estructura que recibes (bloques y cantidades) es obligatoria: ni una pregunta ' ||
     'más ni una menos, y en ese orden.' || chr(10) ||
     '- Por cada riesgo, la pregunta de experiencia pide magnitudes concretas (montos, ' ||
     'volúmenes, cuántas personas, cada cuánto) y la de procedimiento pide el paso a paso ' ||
     'exacto ante el peor escenario. La de procedimiento no se puede fingir: quien lo hizo ' ||
     'lo describe paso a paso; quien lo leyó dice «revisaría bien».' || chr(10) ||
     '- Usa el vocabulario del rubro tal como aparece en la ficha, con las palabras del ' ||
     'dueño. Es lo que vuelve la pregunta específica de este negocio.' || chr(10) ||
     '- El dilema enfrenta dos virtudes reales del negocio que se contradicen. No tiene ' ||
     'respuesta correcta: mide criterio.' || chr(10) ||
     '- La muestra de trabajo, solo si la estructura la pide, va con presencial=true.' || chr(10) ||
     '- Cada pregunta lleva su guía de calificación: c3Esperado (el dato duro que debe ' ||
     'aparecer en una buena respuesta), c4Esperado (la parte incómoda que quien lo vivió ' ||
     'menciona) y senalDeCero (la respuesta que vale 0 por sí sola).' || chr(10) ||
     '- Nunca preguntes por estado civil, hijos, salud, embarazo, religión, política, ' ||
     'sindicato ni origen étnico.' || chr(10) ||
     '- Escribe claro y directo, sin jerga de recursos humanos.',
     true, now());

-- El respaldo en base del doble clic: el chequeo de «hay uno vivo» del código es
-- check-then-insert, y dos peticiones a la vez lo pasan las dos. Este índice hace que la
-- segunda reviente en el insert y nadie pague dos llamadas por el mismo borrador.
CREATE UNIQUE INDEX trabajo_ia_vivo_por_referencia_idx
    ON trabajo_ia (referencia_tabla, referencia_id, agente_codigo)
    WHERE postulacion_id IS NULL AND estado IN ('PENDIENTE', 'EN_CURSO', 'EN_ESPERA');

-- Y el amarre que faltaba: un banco es de vacante si y solo si dice serlo.
ALTER TABLE version_banco ADD CONSTRAINT version_banco_vacante_amarrada_check
    CHECK ((tipo_banco = 'VACANTE') = (vacante_id IS NOT NULL));
