-- El portal del candidato aprende a avisar por dentro (14/09/2026).
--
-- Hasta hoy el sistema solo sabía avisar de una forma: mandando un correo. Y el correo se
-- pierde —cae en promociones, se marca leído sin abrir, llega a una dirección que el
-- cargador de currículums inventó y que nadie mira—. Cuando el candidato entra al portal,
-- lo que pasó mientras no estaba no está en ninguna parte: la lista de sus postulaciones
-- se ve exactamente igual el día que todo sigue igual y el día que le cambiaron el sueldo.
--
-- Esta tabla es la otra mitad: lo que pasó queda esperándolo DENTRO, hasta que lo vea.
--
-- Nace con un solo tipo de aviso —REMUNERACION_ACTUALIZADA, de la V54— y está construida
-- para los que vengan: «avanzaste de etapa», «tienes una prueba por rendir», «te queda un
-- día». Hoy esos avisos existen solo como correos que salen y no vuelven.
CREATE TABLE aviso_portal (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- A quién. Del usuario y no de la persona: la campana es de quien entra al portal, y
    -- es el usuario el que tiene sesión.
    usuario_id      bigint NOT NULL REFERENCES usuario(id),
    -- De qué empresa viene. La misma regla que la postulación: el aviso nace en la
    -- organización DE LA VACANTE, porque es esa empresa la que hizo algo que contar.
    organizacion_id bigint NOT NULL REFERENCES organizacion(id),
    tipo            text NOT NULL,
    -- El texto YA ARMADO, no una plantilla con variables.
    --
    -- Es la misma decisión que correo_enviado: lo que se le dijo al candidato queda escrito
    -- tal como salió. Un aviso que se reconstruyera al leerlo diría el sueldo de hoy, no el
    -- que cambió aquel día, y el aviso dejaría de ser la noticia para volverse un espejo.
    titulo          text NOT NULL,
    cuerpo          text NOT NULL,
    -- A dónde lleva el aviso al pulsarlo. Los dos son opcionales porque no todo aviso
    -- futuro colgará de una postulación («completa tu perfil» no cuelga de ninguna).
    postulacion_id  bigint REFERENCES postulacion(id),
    vacante_id      bigint REFERENCES vacante(id),
    leido_en        timestamptz,
    creado_en       timestamptz NOT NULL DEFAULT now()
);

-- La consulta de la campana, que corre en cada carga del portal: los míos, los no leídos
-- primero, los nuevos arriba. Es el índice que decide si el punto rojo cuesta algo o no.
CREATE INDEX aviso_portal_de_cada_uno
    ON aviso_portal (usuario_id, creado_en DESC);

-- Y el contador del punto: cuántos me quedan sin leer. Parcial porque los leídos son la
-- inmensa mayoría en cuanto la tabla lleve un tiempo viva, y contarlos para descartarlos
-- sería pagar por todo lo que ya no importa.
CREATE INDEX aviso_portal_sin_leer
    ON aviso_portal (usuario_id)
    WHERE leido_en IS NULL;

COMMENT ON TABLE aviso_portal IS
    'La campana del portal del candidato: lo que pasó mientras no estaba, con su estado de '
    'leído. Complementa al correo, no lo sustituye — los dos salen del mismo hecho.';

COMMENT ON COLUMN aviso_portal.tipo IS
    'Qué clase de noticia es. REMUNERACION_ACTUALIZADA es el primero (V54). El portal lo '
    'usa para el icono y para agrupar; el texto de lo que pasó va en titulo y cuerpo.';

COMMENT ON COLUMN aviso_portal.leido_en IS
    'Cuándo lo vio. Vacío: sigue contando para el punto de la campana. Se marca al abrir la '
    'campana, no al abrir la postulación: enterarse de que hay algo es lo que lo apaga.';
