-- ============================================================================
-- Recuperar la contraseña: el enlace de un solo uso que llega por correo
-- ============================================================================
--
-- Hasta aquí, quien olvidaba su contraseña se quedaba fuera. En el portal, la pantalla
-- «¿Olvidaste tu contraseña?» solo explicaba que se escribiera a talento@renaser.pe; en el
-- panel, la única salida era que un administrador invitara de nuevo a la persona.
--
-- Ahora cualquiera de los dos pide un enlace con su correo, le llega por correo, y con él
-- elige una contraseña nueva. Esta tabla guarda esos enlaces.
--
--
-- POR QUE SE GUARDA EL HASH Y NO EL TOKEN
--
-- Lo mismo que enlace_acceso (V24) e invitacion (V37): 32 bytes de azar, y se guarda solo
-- su SHA-256 en hexadecimal. El token de verdad existe una sola vez, dentro del correo.
--
--
-- POR QUE ES DE UN SOLO USO Y VIVE POCO
--
-- Al revés que el enlace de acceso, este cambia la llave de la cuenta: quien lo tenga
-- decide la contraseña. Por eso vale una vez (usado_en), vence pronto (60 minutos por
-- defecto, parámetro minutos_vida_recuperacion) y pedir otro deja sin efecto el anterior
-- (invalidado_en). Abrir el enlace no lo gasta —los clientes de correo los precargan—:
-- solo lo gasta guardar la contraseña nueva.
--
--
-- POR QUE CUELGA DE LA CUENTA Y NO DEL CORREO
--
-- Un mismo correo puede tener cuenta de equipo en dos empresas, y cada una tiene su
-- contraseña. Cada enlace cambia solo la de su cuenta.

CREATE TABLE recuperacion_clave (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- ON DELETE CASCADE: un enlace sin cuenta no sirve para nada, y no debe impedir
    -- retirar una cuenta de prueba. Las cuentas reales no se borran (el borrado de datos
    -- las anonimiza y desactiva), así que en la práctica solo afecta a las de prueba.
    usuario_id     bigint      NOT NULL REFERENCES usuario(id) ON DELETE CASCADE,
    -- SHA-256 del token en hexadecimal: 64 caracteres.
    token_hash     text        NOT NULL UNIQUE,
    creado_en      timestamptz NOT NULL DEFAULT now(),
    vence_en       timestamptz NOT NULL,
    -- Se llena al guardar la contraseña nueva. Un enlace usado no vuelve a servir.
    usado_en       timestamptz,
    -- Se llena cuando la misma cuenta pide otro enlace: vale solo el último.
    invalidado_en  timestamptz,
    CONSTRAINT recuperacion_clave_vence_despues CHECK (vence_en > creado_en)
);

COMMENT ON TABLE recuperacion_clave IS
    'Enlaces para elegir una contraseña nueva. Se guarda el hash, nunca el token. Un solo uso.';

-- Cuántos enlaces pidió una cuenta en la última hora: el límite de solicitudes se cuenta
-- con esta consulta, acotada por fecha, así que la tabla puede crecer sin que se note.
CREATE INDEX recuperacion_clave_usuario_idx ON recuperacion_clave (usuario_id, creado_en);

-- Solo uno vivo por cuenta. Lo que garantiza que el enlace del primer correo deje de
-- servir cuando se pide el segundo no es solo el código: si dos solicitudes simultáneas
-- se cruzaran, la base rechaza la segunda en vez de dejar dos enlaces válidos.
CREATE UNIQUE INDEX recuperacion_clave_una_viva_idx ON recuperacion_clave (usuario_id)
    WHERE usado_en IS NULL AND invalidado_en IS NULL;


-- ============================================================================
-- Cuánto vale un enlace y cuántos se pueden pedir
-- ============================================================================
--
-- Parámetros de la plataforma, como los del bloqueo del login: antes de identificar a
-- nadie no se sabe de qué empresa es quien escribe, y son la defensa de una puerta que es
-- una sola. Si faltan, el código usa los mismos valores por defecto.
--
-- ⚠️ La pantalla dice «Vale por 60 minutos». Si se cambia minutos_vida_recuperacion,
-- ese texto del portal y del panel hay que cambiarlo a mano: la respuesta de la solicitud
-- es siempre la misma y vacía, a propósito, y no puede llevar el número.

INSERT INTO parametro (organizacion_id, codigo, valor, tipo, descripcion)
SELECT o.id, 'minutos_vida_recuperacion', '60', 'ENTERO',
       'Cuántos minutos vale el enlace para elegir una contraseña nueva'
FROM organizacion o
WHERE o.es_plataforma
ON CONFLICT (organizacion_id, codigo) DO NOTHING;

INSERT INTO parametro (organizacion_id, codigo, valor, tipo, descripcion)
SELECT o.id, 'max_recuperaciones_por_hora', '3', 'ENTERO',
       'Cuántos enlaces de contraseña nueva puede recibir una misma cuenta en una hora'
FROM organizacion o
WHERE o.es_plataforma
ON CONFLICT (organizacion_id, codigo) DO NOTHING;

INSERT INTO parametro (organizacion_id, codigo, valor, tipo, descripcion)
SELECT o.id, 'max_recuperaciones_por_ip_hora', '30', 'ENTERO',
       'Cuántas solicitudes de contraseña nueva se atienden desde una misma dirección IP en una hora'
FROM organizacion o
WHERE o.es_plataforma
ON CONFLICT (organizacion_id, codigo) DO NOTHING;


-- ============================================================================
-- Los dos correos
-- ============================================================================
--
-- De la plataforma, como la invitación (V37). Las empresas que se den de alta a partir de
-- ahora reciben copia (ServicioPlataformaImpl copia las plantillas activas); las que ya
-- existen no la tienen, y por eso el envío cae a la de la plataforma cuando a la empresa
-- le falta. No se reescribe ninguna existente: si alguien ya creó una con este código, se
-- respeta.
--
-- ⚠️ Ninguna frase termina en {{nombre_empresa}}: la plataforma se llama «RENASER
-- CONSULTING S.A.C.», con punto final, y el punto de la frase saldría repetido («S.A.C..»).

INSERT INTO plantilla_correo (organizacion_id, codigo, version, asunto, cuerpo, es_activa)
SELECT o.id, 'RECUPERAR_CLAVE_CANDIDATO', 1,
       'Elige una contraseña nueva para tu cuenta',
       'Hola:' || E'\n\n'
           || 'En el portal de empleo de {{nombre_empresa}}, alguien pidió cambiar la contraseña de tu cuenta. '
           || 'Si fuiste tú, abre este enlace y elige una contraseña nueva:' || E'\n\n'
           || '{{enlace}}' || E'\n\n'
           || 'El enlace sirve una sola vez y vence el {{vence}}. Si pides otro, este deja de funcionar.' || E'\n\n'
           || 'Si no lo pediste, ignora este correo: tu contraseña sigue siendo la misma.' || E'\n\n'
           || 'Equipo de Talento · Renaser',
       true
FROM organizacion o
WHERE o.es_plataforma
  AND NOT EXISTS (SELECT 1 FROM plantilla_correo pc
                   WHERE pc.organizacion_id = o.id AND pc.codigo = 'RECUPERAR_CLAVE_CANDIDATO');

INSERT INTO plantilla_correo (organizacion_id, codigo, version, asunto, cuerpo, es_activa)
SELECT o.id, 'RECUPERAR_CLAVE_EQUIPO', 1,
       'Elige una contraseña nueva para el panel de {{nombre_empresa}}',
       'Hola:' || E'\n\n'
           || 'Alguien pidió cambiar la contraseña de tu cuenta del panel de {{nombre_empresa}} '
           || 'en la plataforma de selección de Renaser. '
           || 'Si fuiste tú, abre este enlace y elige una contraseña nueva:' || E'\n\n'
           || '{{enlace}}' || E'\n\n'
           || 'Este enlace cambia solo la contraseña de tu cuenta de {{nombre_empresa}} y de ninguna otra. '
           || 'Si también tienes cuenta en otra empresa, te llega un correo aparte para ella.' || E'\n\n'
           || 'Sirve una sola vez y vence el {{vence}}. Si pides otro, este deja de funcionar.' || E'\n\n'
           || 'Si no lo pediste, ignora este correo: tu contraseña sigue siendo la misma.' || E'\n\n'
           || 'Equipo de Talento · Renaser',
       true
FROM organizacion o
WHERE o.es_plataforma
  AND NOT EXISTS (SELECT 1 FROM plantilla_correo pc
                   WHERE pc.organizacion_id = o.id AND pc.codigo = 'RECUPERAR_CLAVE_EQUIPO');
