-- Las empresas reseñan a quien contrataron por EX (28/09/2026).
--
-- La empresa que contrató a alguien le deja, a partir del primer mes, de 1 a 5 estrellas y
-- una opinión escrita. La persona la lee en su perfil, puede responderla y reportarla; las
-- demás empresas la leen cuando esa persona se postula a sus vacantes.
--
-- ⚠️ Esto rompe A PROPÓSITO una regla escrita del 25/08 —«entre empresas viaja solo el
-- perfil; jamás notas, alertas ni decisiones de otro proceso»—. Lo decidió el usuario el
-- 28/09/2026. Las reseñas NO influyen en nada: ni en notas, ni en el orden del ranking, ni
-- en el pase automático, ni en la IA. Solo se leen.
--
-- Tres tablas: la reseña, su respuesta (una como mucho, sin hilo) y los reportes que
-- revisa la plataforma. Y tres permisos: escribir, leer y moderar.

-- ============================================================================
-- 1 · La reseña
-- ============================================================================
CREATE TABLE resena (
    id                     bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- La contratación reseñada. Única MIENTRAS la reseña está viva: si la empresa la borra,
    -- la contratación vuelve a quedar libre y se puede escribir otra.
    postulacion_id         bigint NOT NULL REFERENCES postulacion(id),
    -- La empresa autora: la firma es de la empresa, no de quien la escribió.
    organizacion_id        bigint NOT NULL REFERENCES organizacion(id),
    -- La persona reseñada. Por persona y no por usuario: es su reputación, la misma en todas
    -- sus cuentas y en todas las empresas.
    persona_id             bigint NOT NULL REFERENCES persona(id),
    estrellas              integer NOT NULL CHECK (estrellas BETWEEN 1 AND 5),
    texto                  text NOT NULL CHECK (char_length(btrim(texto)) BETWEEN 30 AND 1000),
    -- Quién la escribió, solo para auditoría: no se enseña en ninguna pantalla.
    escrita_por_usuario_id bigint NOT NULL REFERENCES usuario(id),
    -- La primera publicación. El plazo de 30 días para editarla o borrarla cuenta desde aquí,
    -- y una edición NO lo alarga.
    publicada_en           timestamptz NOT NULL,
    editada_en             timestamptz,
    -- Ocultada por la plataforma tras un reporte. Es definitivo: deja de verse y de contar
    -- para todos, y la empresa autora la ve atenuada con la nota.
    ocultada_en            timestamptz,
    nota_ocultacion        text,
    -- Borrada por la empresa dentro de su plazo. Se conserva la fila para que el reporte que
    -- tuviera pendiente pueda cerrarse como «retirada».
    borrada_en             timestamptz,
    CHECK ((ocultada_en IS NULL) = (nota_ocultacion IS NULL))
);

-- Una por contratación mientras viva: la unicidad la garantiza la base, no la pantalla. Dos
-- personas de la misma empresa pulsando «Publicar» a la vez no dejan dos reseñas.
CREATE UNIQUE INDEX resena_una_viva_por_contratacion
    ON resena (postulacion_id)
    WHERE borrada_en IS NULL;

-- Lo que piden el perfil, la ficha y la tabla: las reseñas vivas de una persona.
CREATE INDEX resena_de_la_persona
    ON resena (persona_id)
    WHERE borrada_en IS NULL;

COMMENT ON TABLE resena IS
    'La opinión de una empresa sobre quien contrató por EX: estrellas de 1 a 5 y un texto de '
    '30 a 1000 caracteres. Una viva por contratación. La leen la persona y las demás empresas '
    'donde postula. NO puntúa: no entra en notas, ranking, pase automático ni IA.';

-- ============================================================================
-- 2 · La respuesta de la persona
-- ============================================================================
CREATE TABLE respuesta_resena (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    resena_id       bigint NOT NULL REFERENCES resena(id),
    -- La cuenta del portal que respondió.
    usuario_id      bigint NOT NULL REFERENCES usuario(id),
    texto           text NOT NULL CHECK (char_length(btrim(texto)) BETWEEN 30 AND 500),
    publicada_en    timestamptz NOT NULL,
    editada_en      timestamptz,
    -- Hasta cuándo la puede cambiar. Guardado y no calculado porque SE MUEVE: cuando la
    -- empresa edita una reseña ya respondida, la persona recibe un mes entero desde esa
    -- edición para ajustar su respuesta a lo que ahora dice la reseña.
    editable_hasta  timestamptz NOT NULL,
    -- Ocultada por la plataforma tras un reporte de la empresa autora. Definitivo: la persona
    -- la ve atenuada y no puede editarla, borrarla ni responder de nuevo a esa reseña.
    ocultada_en     timestamptz,
    nota_ocultacion text,
    borrada_en      timestamptz,
    CHECK ((ocultada_en IS NULL) = (nota_ocultacion IS NULL))
);

-- Una por reseña mientras viva. Sin hilo: la empresa no contesta a la respuesta.
CREATE UNIQUE INDEX respuesta_una_viva_por_resena
    ON respuesta_resena (resena_id)
    WHERE borrada_en IS NULL;

COMMENT ON TABLE respuesta_resena IS
    'La versión de la persona reseñada, debajo de la reseña. Una viva por reseña, de 30 a 500 '
    'caracteres. Va con su reseña: si la empresa la borra, se borra con ella; si la plataforma '
    'la oculta, deja de verse con ella, pero sigue en la descarga de datos de la persona.';

COMMENT ON COLUMN respuesta_resena.editable_hasta IS
    'Hasta cuándo la persona puede editarla o borrarla. Nace a 30 días de publicarla y vuelve '
    'a 30 días cada vez que la empresa edita la reseña ya respondida.';

-- ============================================================================
-- 3 · Los reportes que revisa la plataforma
-- ============================================================================
CREATE TABLE reporte_resena (
    id                         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    resena_id                  bigint NOT NULL REFERENCES resena(id),
    -- Solo cuando se reporta la respuesta: lo que se juzga es ella, y la reseña va de contexto.
    respuesta_id               bigint REFERENCES respuesta_resena(id),
    objeto                     text NOT NULL CHECK (objeto IN ('RESENA', 'RESPUESTA')),
    -- La persona reseñada (reporta la reseña) o un usuario de la empresa autora (reporta la
    -- respuesta).
    reportado_por_usuario_id   bigint NOT NULL REFERENCES usuario(id),
    -- La empresa autora cuando la que reporta es ella. Vacía cuando reporta la persona.
    organizacion_reportante_id bigint REFERENCES organizacion(id),
    motivo                     text NOT NULL CHECK (motivo IN ('OFENSIVA', 'DATOS_PERSONALES',
                                                               'DISCRIMINATORIA', 'FALSA', 'OTRO')),
    comentario                 text CHECK (comentario IS NULL OR char_length(comentario) <= 500),
    reportado_en               timestamptz NOT NULL,
    -- PENDIENTE hasta que la plataforma decide. RETIRADA cuando la empresa borra la reseña, o
    -- la persona su respuesta, antes de que nadie lo revise.
    estado                     text NOT NULL DEFAULT 'PENDIENTE'
                               CHECK (estado IN ('PENDIENTE', 'MANTENIDA', 'OCULTADA', 'RETIRADA')),
    resuelto_por_usuario_id    bigint REFERENCES usuario(id),
    resuelto_en                timestamptz,
    nota_revision              text,
    CHECK ((objeto = 'RESENA') = (respuesta_id IS NULL)),
    CHECK ((objeto = 'RESPUESTA') = (organizacion_reportante_id IS NOT NULL)),
    -- «Otro motivo» sin explicar no le dice nada a quien revisa.
    CHECK (motivo <> 'OTRO' OR char_length(btrim(coalesce(comentario, ''))) > 0),
    CHECK ((estado = 'PENDIENTE') = (resuelto_en IS NULL)),
    -- Mantener u ocultar exigen una nota: es lo que lee la empresa autora, o la persona.
    CHECK (estado NOT IN ('MANTENIDA', 'OCULTADA')
           OR (resuelto_por_usuario_id IS NOT NULL
               AND char_length(btrim(coalesce(nota_revision, ''))) > 0))
);

-- Reportar dos veces lo mismo se rechaza en la base: un solo reporte pendiente por reseña y
-- uno por respuesta. Volver a reportar tras un «mantener» y una edición lo decide el servicio.
CREATE UNIQUE INDEX reporte_uno_pendiente_por_resena
    ON reporte_resena (resena_id)
    WHERE estado = 'PENDIENTE' AND objeto = 'RESENA';

CREATE UNIQUE INDEX reporte_uno_pendiente_por_respuesta
    ON reporte_resena (respuesta_id)
    WHERE estado = 'PENDIENTE' AND objeto = 'RESPUESTA';

-- La lista de pendientes de la moderación, de la más antigua a la más reciente.
CREATE INDEX reporte_resena_pendientes
    ON reporte_resena (reportado_en)
    WHERE estado = 'PENDIENTE';

CREATE INDEX reporte_resena_de_la_resena ON reporte_resena (resena_id);

COMMENT ON TABLE reporte_resena IS
    'Lo que la persona reporta de una reseña, o la empresa autora de una respuesta. Lo revisa '
    'la plataforma y decide mantener u ocultar, con una nota. Mientras está pendiente, lo '
    'reportado sigue visible y contando: reportar no sirve para esconder una reseña a voluntad.';

-- ============================================================================
-- 4 · Los avisos de la campana
-- ============================================================================
-- Sin tabla nueva: `aviso_portal` guarda el tipo como texto (V56). Los cuatro nuevos no
-- cuelgan de ninguna postulación y llevan a la sección de reseñas del perfil.
COMMENT ON COLUMN aviso_portal.tipo IS
    'Qué clase de noticia es. REMUNERACION_ACTUALIZADA (V55) es el cambio de sueldo hecho '
    'desde la tarjeta del detalle; VACANTE_ACTUALIZADA (V58) es el guardado del formulario '
    'de la vacante, con todo lo que cambió —sueldo incluido— en un solo aviso; '
    'VACANTE_ELIMINADA (V60) es que la empresa retiró la vacante y la postulación quedó '
    'cerrada, y no enlaza a ninguna parte. RESENA_PUBLICADA, RESENA_EDITADA, '
    'REPORTE_RESENA_RESUELTO y RESPUESTA_RESENA_OCULTADA (V63) son de las reseñas de '
    'empresas y llevan a la sección de reseñas del perfil. El portal usa el tipo para el '
    'icono y para el enlace; el texto de lo que pasó va en titulo y cuerpo.';

-- ============================================================================
-- 5 · Los tres permisos
-- ============================================================================
-- resenar_contratado: escribir, editar y borrar la reseña de una contratación de la propia
-- empresa, y reportar la respuesta a esa reseña.
-- ver_resenas_candidato: leer las reseñas de todas las empresas en la ficha, y la columna
-- «Reseñas» de la tabla.
-- moderar_resenas: la pantalla «Reseñas reportadas». SOLO del Administrador de la
-- plataforma, y el alta de empresas lo excluye de la copia (ServicioPlataformaImpl#sembrar),
-- igual que administrar_plataforma. Además el servicio exige ser la plataforma: una empresa
-- que se lo concediera a sí misma en «Permisos» seguiría sin poder moderar.
INSERT INTO permiso (codigo, etiqueta, grupo, orden) VALUES
    ('resenar_contratado',    'Escribir la reseña de una persona contratada',      'CANDIDATOS',    42),
    ('ver_resenas_candidato', 'Ver las reseñas de empresas de un candidato',       'CANDIDATOS',    43),
    ('moderar_resenas',       'Revisar las reseñas y respuestas reportadas',       'CONFIGURACION', 15);

-- Escribir y leer: Talento y Dirección en todas las vacantes, Responsable de área solo en
-- las suyas. En TODAS las organizaciones que ya existen, no solo en la de la plataforma: una
-- empresa dada de alta antes de hoy tiene sus propios roles, y sin esta fila su equipo vería
-- el permiso en la matriz sin tenerlo. Las empresas futuras lo reciben con la copia del alta.
INSERT INTO rol_permiso (rol_id, permiso_id, alcance)
SELECT r.id, p.id,
       CASE r.codigo WHEN 'RESPONSABLE_AREA' THEN 'SUS_VACANTES' ELSE 'TODO' END
FROM rol r
JOIN permiso p ON p.codigo IN ('resenar_contratado', 'ver_resenas_candidato')
WHERE r.codigo IN ('TALENTO', 'RESPONSABLE_AREA', 'DIRECCION')
  AND NOT EXISTS (SELECT 1 FROM rol_permiso ya
                  WHERE ya.rol_id = r.id AND ya.permiso_id = p.id);

INSERT INTO rol_permiso (rol_id, permiso_id, alcance)
SELECT r.id, p.id, 'TODO'
FROM rol r
JOIN permiso p ON p.codigo = 'moderar_resenas'
WHERE r.codigo = 'ADMINISTRADOR'
  AND r.organizacion_id = (SELECT id FROM organizacion WHERE es_plataforma)
  AND NOT EXISTS (SELECT 1 FROM rol_permiso ya
                  WHERE ya.rol_id = r.id AND ya.permiso_id = p.id);
