-- La gestión de personas: la ficha del colaborador y el mapa de la empresa (29/09/2026).
--
-- Hasta aquí el sistema terminaba en CONTRATADO: la persona que entraba a trabajar no existía.
-- Esto la crea, aparte de `persona` y del perfil del portal. Son dos cosas distintas con dos
-- bases legales distintas: la cuenta del candidato se borra si lo pide (Ley 29733) y la ficha
-- de quien trabaja se conserva, porque la ley laboral obliga a guardar esos registros. Ninguna
-- FK de aquí apunta a `persona`, a propósito.
--
-- Cinco tablas nuevas y ninguna columna nueva en las viejas:
--
--   · sede               dónde se trabaja. Nueva.
--   · colaborador        quién es: identidad, contacto, domicilio y formación. Se corrige sin
--                        historial (una errata no es un cambio de vida).
--   · periodo_laboral    cada tramo entre un ingreso y un cese. Un reingreso abre otro.
--   · situacion_laboral  dónde está y en qué condiciones, con vigencia desde-hasta. Cada cambio
--                        es una fila; ninguna se borra, las programadas se anulan.
--   · cese_anulado       los ceses que se deshicieron, para que el historial los enseñe tachados.
--   · contratado_sin_alta la contratación que RR.HH. decidió no convertir en ficha.
--
-- ⚠️ Los códigos son los de SUNAT desde el primer día (tablas 3, 12, 17 y 33), para que
-- Planillas los lea sin migrar valores. En pantalla se enseña el texto, nunca el código; la
-- traducción vive en CatalogosDePersonas y la pide el panel.

-- ============ 1 · Sedes ============

CREATE TABLE sede (
    id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organizacion_id    bigint NOT NULL REFERENCES organizacion(id),
    nombre             text NOT NULL CHECK (btrim(nombre) <> ''),
    direccion          text,
    provincia_ubigeo   varchar(6) REFERENCES ubigeo(codigo),
    -- El código de establecimiento que SUNAT asigna a cada local anexo: cuatro cifras.
    codigo_sunat       varchar(4) CHECK (codigo_sunat IS NULL OR codigo_sunat ~ '^[0-9]{4}$'),
    es_activa          boolean NOT NULL DEFAULT true,
    creado_en          timestamptz NOT NULL DEFAULT now()
);

-- Único sin distinguir mayúsculas: la carga por Excel busca la sede por su nombre así, y dos
-- sedes que solo difieren en una mayúscula harían ambigua cada fila del archivo.
CREATE UNIQUE INDEX sede_nombre_unico_por_org ON sede (organizacion_id, lower(btrim(nombre)));

COMMENT ON TABLE sede IS
    'Los locales de la empresa. No se borran: se desactivan, y quien ya estaba en una '
    'desactivada la conserva (V64).';

-- ============ 2 · El colaborador ============

CREATE TABLE colaborador (
    id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organizacion_id         bigint NOT NULL REFERENCES organizacion(id),
    -- Tabla 3 de SUNAT: 01 DNI, 04 carné de extranjería, 07 pasaporte, 23 PTP, 26 CPP.
    tipo_documento          varchar(2) NOT NULL
                            CHECK (tipo_documento IN ('01', '04', '07', '23', '26')),
    numero_documento        text NOT NULL CHECK (numero_documento ~ '^[A-Z0-9]{4,15}$'),
    nombres                 text NOT NULL CHECK (btrim(nombres) <> ''),
    apellido_paterno        text NOT NULL CHECK (btrim(apellido_paterno) <> ''),
    apellido_materno        text,
    fecha_nacimiento        date NOT NULL,
    sexo                    varchar(1) NOT NULL CHECK (sexo IN ('M', 'F')),
    estado_civil            text CHECK (estado_civil IS NULL OR estado_civil IN
                                ('SOLTERO', 'CASADO', 'VIUDO', 'DIVORCIADO', 'CONVIVIENTE')),
    nacionalidad            text,
    celular                 text,
    correo_personal         text,
    correo_corporativo      text,
    direccion               text,
    provincia_ubigeo        varchar(6) REFERENCES ubigeo(codigo),
    nivel_educativo_codigo  text REFERENCES nivel_educativo(codigo),
    -- De qué contratación salió la ficha, si vino de selección. El periodo también la guarda:
    -- esta es la del alta, aquella la de cada periodo (un reingreso puede venir de otra).
    postulacion_id          bigint REFERENCES postulacion(id),
    creado_por_usuario_id   bigint REFERENCES usuario(id),
    creado_en               timestamptz NOT NULL DEFAULT now(),
    actualizado_en          timestamptz NOT NULL DEFAULT now(),
    -- Nunca dos fichas del mismo documento en la misma empresa. En otra empresa, sí.
    UNIQUE (organizacion_id, tipo_documento, numero_documento)
);

CREATE INDEX colaborador_orden_idx
    ON colaborador (organizacion_id, apellido_paterno, apellido_materno, nombres);

COMMENT ON TABLE colaborador IS
    'La ficha de quien trabaja en la empresa (V64). Independiente de persona y del perfil del '
    'portal: el borrado de la Ley 29733 y la retención de 2 años no la tocan (art. 14.5, '
    'pendiente de validar con el abogado). Editar sus datos es corregir: no deja historial, '
    'deja una fila en auditoria con el valor anterior y el nuevo.';

-- ============ 3 · Los periodos ============

CREATE TABLE periodo_laboral (
    id                          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    colaborador_id              bigint NOT NULL REFERENCES colaborador(id),
    fecha_ingreso               date NOT NULL,
    -- El último día trabajado. Hasta ese día inclusive la persona sigue activa.
    fecha_cese                  date,
    -- Tabla 17 de SUNAT, más 99 «otro» (propio: la tabla no tiene un cajón genérico).
    motivo_cese                 varchar(2) CHECK (motivo_cese IS NULL OR motivo_cese IN
                                    ('01', '02', '03', '04', '05', '06', '07', '08', '09',
                                     '17', '99')),
    observacion_cese            text,
    cese_registrado_por_usuario_id bigint REFERENCES usuario(id),
    cese_registrado_en          timestamptz,
    postulacion_id              bigint REFERENCES postulacion(id),
    creado_por_usuario_id       bigint REFERENCES usuario(id),
    creado_en                   timestamptz NOT NULL DEFAULT now(),
    CHECK (fecha_cese IS NULL OR fecha_cese >= fecha_ingreso),
    CHECK ((fecha_cese IS NULL) = (motivo_cese IS NULL))
);

CREATE INDEX periodo_laboral_colaborador_idx ON periodo_laboral (colaborador_id, fecha_ingreso DESC);

-- Cada postulación contratada da como mucho un alta: la primera ficha o un reingreso.
CREATE UNIQUE INDEX periodo_laboral_una_alta_por_postulacion
    ON periodo_laboral (postulacion_id) WHERE postulacion_id IS NOT NULL;

-- Un cese deshecho. Se copia aquí antes de dejar el periodo abierto otra vez, para que el
-- historial lo enseñe tachado con quién lo anuló y por qué.
CREATE TABLE cese_anulado (
    id                          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    periodo_id                  bigint NOT NULL REFERENCES periodo_laboral(id),
    fecha_cese                  date NOT NULL,
    motivo_cese                 varchar(2) NOT NULL,
    observacion_cese            text,
    registrado_por_usuario_id   bigint REFERENCES usuario(id),
    registrado_en               timestamptz,
    anulado_por_usuario_id      bigint REFERENCES usuario(id),
    anulado_en                  timestamptz NOT NULL DEFAULT now(),
    motivo_anulacion            text NOT NULL CHECK (btrim(motivo_anulacion) <> '')
);

CREATE INDEX cese_anulado_periodo_idx ON cese_anulado (periodo_id);

-- ============ 4 · La situación laboral ============

CREATE TABLE situacion_laboral (
    id                          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    colaborador_id              bigint NOT NULL REFERENCES colaborador(id),
    periodo_id                  bigint NOT NULL REFERENCES periodo_laboral(id),
    vigente_desde               date NOT NULL,
    -- Vacío = abierta. Un cambio el mismo día que la anterior la deja en «desde - 1»: un
    -- tramo vacío que sigue en el historial y que ninguna consulta de «hoy» encuentra.
    vigente_hasta               date,
    sede_id                     bigint NOT NULL REFERENCES sede(id),
    area_id                     bigint NOT NULL REFERENCES area(id),
    puesto_id                   bigint NOT NULL REFERENCES puesto(id),
    jefe_colaborador_id         bigint REFERENCES colaborador(id),
    -- Tabla 12 de SUNAT, más el convenio de prácticas como opción propia.
    tipo_contrato               varchar(9) NOT NULL CHECK (tipo_contrato IN
                                    ('01', '02', '03', '04', '05', '06', '07', '08', '09',
                                     '10', '11', '99', 'PRACTICAS')),
    fin_contrato                date,
    fin_periodo_prueba          date,
    -- Tabla 33 de SUNAT.
    regimen_laboral             varchar(2) NOT NULL CHECK (regimen_laboral IN
                                    ('01', '16', '17', '18', '20', '21', '26', '99')),
    -- ⚠️ Solo lo ve y lo escribe quien tiene ver_sueldos. La API no lo envía a nadie más, ni
    -- en la ficha, ni en el historial, ni en la plantilla, ni en la auditoría.
    sueldo_base                 numeric(12, 2) CHECK (sueldo_base IS NULL OR sueldo_base >= 0),
    moneda                      varchar(3) CHECK (moneda IS NULL OR moneda IN ('PEN', 'USD')),
    tipo_motivo                 text NOT NULL CHECK (tipo_motivo IN
                                    ('INGRESO', 'CARGA_INICIAL', 'REINGRESO', 'PROMOCION',
                                     'TRASLADO', 'CAMBIO_JEFE', 'RENOVACION_CONTRATO',
                                     'AJUSTE_REMUNERACION', 'CORRECCION', 'OTRO')),
    detalle_motivo              text,
    registrado_por_usuario_id   bigint REFERENCES usuario(id),
    registrado_en               timestamptz NOT NULL DEFAULT now(),
    anulada_en                  timestamptz,
    anulada_por_usuario_id      bigint REFERENCES usuario(id),
    motivo_anulacion            text,
    CHECK (vigente_hasta IS NULL OR vigente_hasta >= vigente_desde - 1),
    CHECK (sueldo_base IS NULL OR moneda IS NOT NULL),
    CHECK (jefe_colaborador_id IS NULL OR jefe_colaborador_id <> colaborador_id),
    CHECK (tipo_motivo <> 'OTRO' OR (detalle_motivo IS NOT NULL AND btrim(detalle_motivo) <> '')),
    CHECK (anulada_en IS NULL OR (motivo_anulacion IS NOT NULL AND btrim(motivo_anulacion) <> ''))
);

CREATE INDEX situacion_laboral_periodo_idx ON situacion_laboral (periodo_id, vigente_desde);
CREATE INDEX situacion_laboral_colaborador_idx ON situacion_laboral (colaborador_id);
CREATE INDEX situacion_laboral_jefe_idx ON situacion_laboral (jefe_colaborador_id)
    WHERE jefe_colaborador_id IS NOT NULL;
CREATE INDEX situacion_laboral_puesto_idx ON situacion_laboral (puesto_id);
CREATE INDEX situacion_laboral_sede_idx ON situacion_laboral (sede_id);

COMMENT ON TABLE situacion_laboral IS
    'Dónde está alguien y en qué condiciones, desde una fecha (V64). Un cambio cierra la '
    'anterior el día antes y rige desde su fecha, que puede ser futura (programado). Nada se '
    'borra: un cambio ya vigente se corrige con otro de tipo CORRECCION, y uno programado se '
    'anula con motivo.';

-- ============ 5 · Contratados que no se dan de alta ============

CREATE TABLE contratado_sin_alta (
    id                          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organizacion_id             bigint NOT NULL REFERENCES organizacion(id),
    postulacion_id              bigint NOT NULL UNIQUE REFERENCES postulacion(id),
    motivo                      text NOT NULL CHECK (btrim(motivo) <> ''),
    registrado_por_usuario_id   bigint REFERENCES usuario(id),
    registrado_en               timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE contratado_sin_alta IS
    'Una contratación que RR.HH. decidió no convertir en ficha («ya no trabaja aquí»). Solo '
    'la saca del aviso de pendientes; la postulación sigue en CONTRATADO (V64).';

-- ============ 6 · Los cuatro permisos ============
--
-- Grupo nuevo, PERSONAS. Talento y Dirección, con alcance TODO, en TODAS las organizaciones
-- que ya existen —no solo en la plataforma—, igual que la V60: una empresa dada de alta antes
-- de hoy tiene sus propios roles. Las futuras los reciben con la copia de la matriz del alta
-- (ServicioPlataformaImpl#sembrar), porque la plataforma ya los tiene por esta sentencia.
--
-- ⚠️ ver_sueldos solo a Dirección. Está por confirmar con la clienta; si decide otra cosa se
-- cambia en la matriz de Configuración, sin tocar código.
INSERT INTO permiso (codigo, etiqueta, grupo, orden) VALUES
    ('ver_colaboradores',    'Ver los colaboradores y sus fichas',                     'PERSONAS', 1),
    ('editar_colaboradores', 'Dar de alta, editar, cesar y reingresar colaboradores', 'PERSONAS', 2),
    ('ver_sueldos',          'Ver y editar el sueldo de los colaboradores',           'PERSONAS', 3),
    ('editar_estructura',    'Editar las sedes y los cargos',                         'PERSONAS', 4);

INSERT INTO rol_permiso (rol_id, permiso_id, alcance)
SELECT r.id, p.id, 'TODO'
FROM rol r
JOIN permiso p ON p.codigo IN ('ver_colaboradores', 'editar_colaboradores', 'editar_estructura')
WHERE r.codigo IN ('TALENTO', 'DIRECCION')
  AND NOT EXISTS (SELECT 1 FROM rol_permiso ya
                  WHERE ya.rol_id = r.id AND ya.permiso_id = p.id);

INSERT INTO rol_permiso (rol_id, permiso_id, alcance)
SELECT r.id, p.id, 'TODO'
FROM rol r
JOIN permiso p ON p.codigo = 'ver_sueldos'
WHERE r.codigo = 'DIRECCION'
  AND NOT EXISTS (SELECT 1 FROM rol_permiso ya
                  WHERE ya.rol_id = r.id AND ya.permiso_id = p.id);
