-- Un editor de la prueba técnica más simple (05/10/2026).
--
-- Hasta la V67, quien armaba la prueba creaba los entregables aparte y marcaba a mano qué
-- entregables miraba cada criterio («Mira»). Desde aquí los archivos se piden donde se usan
-- —dentro de una pregunta, o como entregable general que cubre toda la prueba o algunas
-- preguntas— y el sistema deduce qué mira cada criterio a partir de ese alcance.
--
-- Lo que se guarda es el alcance; «Mira» se calcula al leer (CalificacionDeLaPruebaPropia):
--   · de una pregunta → la mira el criterio de esa pregunta;
--   · general que cubre toda la prueba → la miran todos los criterios;
--   · general que cubre unas preguntas → la miran los criterios de esas preguntas.
--
-- ⚠️ Las versiones ya publicadas (o archivadas) NO se tocan: sus entregables quedan con el
-- alcance vacío y siguen leyendo su «Mira» marcado a mano en `criterio_banco_entregable`,
-- así que sus notas, su ficha y su ranking no cambian (AC-22). Solo se convierten los
-- borradores, que ningún candidato rinde.

-- ============================================================================
-- 1 · El alcance de cada entregable de la prueba del editor
-- ============================================================================
-- PREGUNTA        = el archivo de una pregunta (`pregunta_id`), como mucho uno por pregunta.
-- TODA_LA_PRUEBA  = un entregable general que reúne el resultado de toda la prueba.
-- PREGUNTAS       = un entregable general que reúne las respuestas de unas preguntas
--                   (las de `entregable_cubre_pregunta`).
-- NULL            = un entregable de antes (V67), con «Mira» marcado a mano, o uno de una
--                   plantilla de prueba, que no tiene criterios.
ALTER TABLE entregable_requerido
    ADD COLUMN alcance text
        CHECK (alcance IS NULL OR alcance IN ('PREGUNTA', 'TODA_LA_PRUEBA', 'PREGUNTAS')),
    ADD COLUMN pregunta_id bigint REFERENCES pregunta(id);
ALTER TABLE entregable_requerido ADD CONSTRAINT entregable_requerido_alcance_pregunta_check
    CHECK ((pregunta_id IS NOT NULL) = (alcance IS NOT DISTINCT FROM 'PREGUNTA'));
ALTER TABLE entregable_requerido ADD CONSTRAINT entregable_requerido_alcance_del_editor_check
    CHECK (alcance IS NULL OR version_banco_id IS NOT NULL);
-- Una pregunta pide como mucho un archivo: un doble envío no crea dos.
CREATE UNIQUE INDEX entregable_requerido_uno_por_pregunta_idx
    ON entregable_requerido (pregunta_id) WHERE pregunta_id IS NOT NULL;
COMMENT ON COLUMN entregable_requerido.alcance IS
    'Solo en la prueba del editor (V68): PREGUNTA (el archivo de pregunta_id), TODA_LA_PRUEBA '
    'o PREGUNTAS (las de entregable_cubre_pregunta). NULL = de antes de la V68, con «Mira» '
    'marcado a mano en criterio_banco_entregable, o de una plantilla.';

-- Las preguntas que cubre un entregable general de alcance PREGUNTAS.
CREATE TABLE entregable_cubre_pregunta (
    id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entregable_requerido_id bigint NOT NULL REFERENCES entregable_requerido(id),
    pregunta_id             bigint NOT NULL REFERENCES pregunta(id),
    creado_en               timestamptz NOT NULL DEFAULT now(),
    UNIQUE (entregable_requerido_id, pregunta_id)
);
CREATE INDEX entregable_cubre_pregunta_pregunta_idx ON entregable_cubre_pregunta (pregunta_id);

COMMENT ON TABLE criterio_banco_entregable IS
    'Lo que miraba cada criterio, marcado a mano (V67). Desde la V68 solo lo leen las versiones '
    'publicadas antes de esa fecha: en las nuevas «Mira» se deduce del alcance de los entregables.';

-- ============================================================================
-- 2 · Los borradores abiertos pasan al modelo nuevo
-- ============================================================================
-- Sus entregables pasan a generales que cubren las preguntas de los criterios que los
-- miraban. Si alguno de esos criterios no tenía preguntas, el general cubre toda la prueba.
-- Un entregable que no miraba nadie queda general sin cubrir: sale como falta al publicar.
UPDATE entregable_requerido e
   SET alcance = 'TODA_LA_PRUEBA'
 WHERE e.version_banco_id IN (SELECT v.id FROM version_banco v
                               WHERE v.proposito = 'PRUEBA_PUESTO' AND v.estado = 'BORRADOR')
   AND EXISTS (SELECT 1 FROM criterio_banco_entregable m
                WHERE m.entregable_requerido_id = e.id
                  AND NOT EXISTS (SELECT 1 FROM pregunta p
                                   WHERE p.criterio_banco_id = m.criterio_banco_id));

UPDATE entregable_requerido e
   SET alcance = 'PREGUNTAS'
 WHERE e.alcance IS NULL
   AND e.version_banco_id IN (SELECT v.id FROM version_banco v
                               WHERE v.proposito = 'PRUEBA_PUESTO' AND v.estado = 'BORRADOR');

INSERT INTO entregable_cubre_pregunta (entregable_requerido_id, pregunta_id)
SELECT DISTINCT e.id, p.id
  FROM entregable_requerido e
  JOIN criterio_banco_entregable m ON m.entregable_requerido_id = e.id
  JOIN pregunta p ON p.criterio_banco_id = m.criterio_banco_id
 WHERE e.alcance = 'PREGUNTAS';

-- Lo que miraban sus criterios ya no se lee: ahora sale del alcance.
DELETE FROM criterio_banco_entregable m
 USING criterio_banco c, version_banco v
 WHERE m.criterio_banco_id = c.id
   AND c.version_banco_id = v.id
   AND v.proposito = 'PRUEBA_PUESTO'
   AND v.estado = 'BORRADOR';

-- ============================================================================
-- 3 · Sin días: «Cronometrada» o «Sin cronómetro»
-- ============================================================================
-- «Sin cronómetro» reutiliza PLAZO_ABIERTO con plazo_dias vacío: se trabaja hasta la fecha
-- límite de la vacante. Los borradores dejan de tener días; las publicadas sin fecha los
-- conservan y siguen contándolos desde que se abre, como hasta hoy.
UPDATE version_banco
   SET plazo_dias = NULL
 WHERE proposito = 'PRUEBA_PUESTO' AND estado = 'BORRADOR' AND plazo_dias IS NOT NULL;
