-- La prueba al instante, la campana en cada etapa y los recordatorios (07/10/2026).
--
-- Muchos candidatos se pierden entre una etapa y la siguiente: entregan el banco, leen «te
-- avisaremos cuando avance», cierran la página y no vuelven. Esta migración prepara tres de
-- los cuatro cambios de specs/la-prueba-al-instante-y-avisos-de-etapa.md (el cuarto, abrir la
-- prueba al instante, no toca el esquema):
--
--   1. Cada transición recuerda CÓMO se enteró el candidato. Es lo que permite que un
--      recordatorio no le cuente a nadie lo que el equipo decidió no contarle.
--   2. Una tabla que dice qué recordatorio salió para qué turno, para no repetirlo nunca.
--   3. Los parámetros y los dos textos de correo de los recordatorios, en todas las empresas.
--   4. El texto de PRUEBA_DISPONIBLE deja de decir «desde este correo», que ya no es verdad.

-- ============================================================================
-- 1 · Cómo se enteró el candidato de cada transición
-- ============================================================================
-- Hasta hoy solo quedaba escrito en el motivo («· sin avisar al candidato») y en la auditoría,
-- y el motivo no siempre existe: una transición del sistema callada no dejaba marca ninguna.
--
-- Vacía en todo lo anterior a esta migración, y eso es a propósito: los recordatorios solo
-- cuentan los turnos que se abren con CORREO, así que un turno abierto antes del despliegue
-- nunca recibe un recordatorio de golpe. Sin esto, el primer día saldría una ráfaga de correos
-- a todo el que lleva más de 24 horas en su turno.
--
-- ⚠️ `transicion_estado` es inmutable (trigger de la V6), pero añadir una columna no actualiza
-- ninguna fila: las viejas leen NULL sin que el trigger salte.
ALTER TABLE transicion_estado
    ADD COLUMN aviso_al_candidato text
        CONSTRAINT transicion_aviso_al_candidato_check
        CHECK (aviso_al_candidato IS NULL
               OR aviso_al_candidato IN ('CORREO', 'NINGUNO', 'POR_LA_CAMPANA'));

COMMENT ON COLUMN transicion_estado.aviso_al_candidato IS
    'Cómo se enteró el candidato: CORREO (el correo y la campana), NINGUNO (el equipo decidió '
    'no contárselo) o POR_LA_CAMPANA (solo el aviso propio, como el cierre por vacante '
    'eliminada). Vacía en las transiciones anteriores a la V70.';

-- ============================================================================
-- 2 · Qué recordatorio salió para qué turno
-- ============================================================================
-- El turno es la transición que lo abrió: si el candidato vuelve a entrar en el mismo estado
-- —se le reabre la evaluación, se le retrocede—, es otra transición y otro turno, con sus dos
-- recordatorios.
--
-- TRAS_ENTRAR sale una vez por turno. ANTES_DEL_PLAZO, una vez por turno y por fecha: si la
-- fecha se mueve después del recordatorio, puede volver a salir para la nueva, una sola vez.
--
-- OMITIDO es «este ya no sale»: cuando el del plazo se adelanta al de las 24 horas (o caen a
-- menos de 12 horas el uno del otro), el de las 24 horas se da por gastado. Queda escrito para
-- que el sondeo no lo vuelva a considerar cada minuto.
CREATE TABLE recordatorio_enviado (
    id                   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    postulacion_id       bigint NOT NULL REFERENCES postulacion(id),
    transicion_estado_id bigint NOT NULL REFERENCES transicion_estado(id),
    tipo                 text NOT NULL
        CONSTRAINT recordatorio_enviado_tipo_check
        CHECK (tipo IN ('TRAS_ENTRAR', 'ANTES_DEL_PLAZO')),
    -- La fecha que se recordó. Solo la lleva el del plazo.
    plazo_en             timestamptz,
    resultado            text NOT NULL
        CONSTRAINT recordatorio_enviado_resultado_check
        CHECK (resultado IN ('ENVIADO', 'OMITIDO')),
    creado_en            timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT recordatorio_enviado_plazo_check
        CHECK ((tipo = 'ANTES_DEL_PLAZO') = (plazo_en IS NOT NULL))
);

-- La red de la base debajo del «¿ya salió?» del código: reiniciar el servidor, o dos sondeos
-- a la vez, no pueden mandar el mismo recordatorio dos veces.
CREATE UNIQUE INDEX recordatorio_tras_entrar_una_vez
    ON recordatorio_enviado (transicion_estado_id)
    WHERE tipo = 'TRAS_ENTRAR';

CREATE UNIQUE INDEX recordatorio_antes_del_plazo_una_vez
    ON recordatorio_enviado (transicion_estado_id, plazo_en)
    WHERE tipo = 'ANTES_DEL_PLAZO';

CREATE INDEX recordatorio_enviado_postulacion_idx ON recordatorio_enviado (postulacion_id);

COMMENT ON TABLE recordatorio_enviado IS
    'Qué recordatorio salió (o se dio por omitido) para qué turno de una postulación. Es lo que '
    'impide repetirlo al reiniciar el servidor (V70).';

-- ============================================================================
-- 3 · Los parámetros y los textos de los recordatorios
-- ============================================================================
-- En TODAS las organizaciones y no solo en la plataforma. ServicioCorreo.enviar no cae a la
-- plataforma cuando a una empresa le falta un texto, y un parámetro que no existe no se puede
-- editar desde el panel (editarParametro no crea filas). Las empresas que se den de alta
-- después los copian de la plataforma, como copian todos los demás.
INSERT INTO parametro (organizacion_id, codigo, valor, tipo, descripcion, creado_en)
SELECT o.id, 'recordatorios_activos', 'true', 'BOOLEANO',
       'Si se manda a los candidatos un recordatorio (correo y campana) cuando no han '
           || 'entregado su evaluación o no han empezado su prueba',
       now()
  FROM organizacion o
 WHERE NOT EXISTS (SELECT 1 FROM parametro p
                    WHERE p.organizacion_id = o.id AND p.codigo = 'recordatorios_activos');

INSERT INTO parametro (organizacion_id, codigo, valor, tipo, descripcion, creado_en)
SELECT o.id, 'recordatorio_horas_tras_el_turno', '24', 'ENTERO',
       'Horas desde que le toca la evaluación o la prueba hasta el primer recordatorio',
       now()
  FROM organizacion o
 WHERE NOT EXISTS (SELECT 1 FROM parametro p
                    WHERE p.organizacion_id = o.id
                      AND p.codigo = 'recordatorio_horas_tras_el_turno');

INSERT INTO parametro (organizacion_id, codigo, valor, tipo, descripcion, creado_en)
SELECT o.id, 'recordatorio_horas_antes_del_plazo', '24', 'ENTERO',
       'Horas antes de que venza la evaluación o la prueba en que sale el segundo recordatorio',
       now()
  FROM organizacion o
 WHERE NOT EXISTS (SELECT 1 FROM parametro p
                    WHERE p.organizacion_id = o.id
                      AND p.codigo = 'recordatorio_horas_antes_del_plazo');

-- {{aviso}} es la frase que pone el sistema según el recordatorio: «Aún no has respondido tu
-- evaluación para X» o «Tu evaluación para X vence el vie 10/10 a las 23:59». Un solo texto
-- por etapa sirve a los dos momentos y se edita en un solo sitio.
INSERT INTO plantilla_correo (organizacion_id, codigo, version, asunto, cuerpo, es_activa, creado_en)
SELECT o.id, 'RECORDATORIO_EVALUACION', 1,
       '{{aviso}}',
       'Hola {{nombre}}:' || chr(10) || chr(10) ||
       '{{aviso}}.' || chr(10) || chr(10) ||
       'Tus respuestas se guardan solas: puedes empezar ahora y terminarla después, siempre '
           || 'antes de que venza.' || chr(10) || chr(10) ||
       'Entra desde aquí:' || chr(10) ||
       '{{enlace}}' || chr(10) || chr(10) ||
       'O entra en el portal con tu correo y tu contraseña y abre «Mis procesos».' || chr(10) || chr(10) ||
       'Si tienes cualquier duda, responde a este correo.' || chr(10) || chr(10) ||
       'Equipo de Talento — Renaser',
       true, now()
  FROM organizacion o
 WHERE NOT EXISTS (SELECT 1 FROM plantilla_correo pc
                    WHERE pc.organizacion_id = o.id AND pc.codigo = 'RECORDATORIO_EVALUACION');

INSERT INTO plantilla_correo (organizacion_id, codigo, version, asunto, cuerpo, es_activa, creado_en)
SELECT o.id, 'RECORDATORIO_PRUEBA', 1,
       '{{aviso}}',
       'Hola {{nombre}}:' || chr(10) || chr(10) ||
       '{{aviso}}.' || chr(10) || chr(10) ||
       'Si tu prueba tiene tiempo, empieza a contar cuando la abras y confirmes, no antes.'
           || chr(10) || chr(10) ||
       'Entra desde aquí:' || chr(10) ||
       '{{enlace}}' || chr(10) || chr(10) ||
       'O entra en el portal con tu correo y tu contraseña y abre «Mis procesos».' || chr(10) || chr(10) ||
       'Si tienes cualquier duda, responde a este correo.' || chr(10) || chr(10) ||
       'Equipo de Talento — Renaser',
       true, now()
  FROM organizacion o
 WHERE NOT EXISTS (SELECT 1 FROM plantilla_correo pc
                    WHERE pc.organizacion_id = o.id AND pc.codigo = 'RECORDATORIO_PRUEBA');

-- ============================================================================
-- 4 · PRUEBA_DISPONIBLE deja de decir «desde este correo»
-- ============================================================================
-- El texto original (V29) dice «Tienes {{plazo}} desde este correo.», y ya no es verdad: el
-- reloj arranca al abrir la prueba, no al recibir el correo, y desde la V70 {{plazo}} dice el
-- tiempo y la fecha límite («90 minutos desde que la empieces, hasta el vie 10/10 a las 23:59»).
--
-- La versión activa de producción se editó a mano y no está en ninguna migración, así que esto
-- funciona con cualquier texto: solo toca los que dicen «desde este correo», y de ellos solo esa
-- frase. Lo demás —la línea de cómo entrar al portal, la firma— se queda como esté.
--
-- Alcance: PRUEBA_DISPONIBLE de cada organización y los textos propios que alguna vacante use
-- para ese aviso (plantilla_correo_vacante con aviso_codigo = 'PRUEBA_DISPONIBLE').
--
-- La sustitución, en tres pasos y en este orden:
--   a) «Tienes {{plazo}} desde este correo» → «Tienes {{plazo}}» (la de la V29; el punto se queda);
--   b) «{{plazo}} desde este correo» → «{{plazo}}» (cualquier otra frase que siga a la variable);
--   c) cualquier otra frase que aún diga «desde este correo», con o sin mayúsculas, se sustituye
--      entera por la del texto de referencia: «Tienes {{plazo}}.».
--
-- Como siempre que se edita un texto, se publica una versión nueva y la anterior se conserva
-- desactivada: cada correo enviado apunta a la versión con la que salió.
WITH en_alcance AS (
    SELECT DISTINCT ON (pc.organizacion_id, pc.codigo)
           pc.organizacion_id, pc.codigo, pc.asunto, pc.cuerpo
      FROM plantilla_correo pc
     WHERE pc.es_activa
       AND (pc.codigo = 'PRUEBA_DISPONIBLE'
            OR EXISTS (SELECT 1
                         FROM plantilla_correo_vacante pcv
                         JOIN vacante v ON v.id = pcv.vacante_id
                        WHERE pcv.aviso_codigo = 'PRUEBA_DISPONIBLE'
                          AND pcv.plantilla_codigo = pc.codigo
                          AND v.organizacion_id = pc.organizacion_id))
     ORDER BY pc.organizacion_id, pc.codigo, pc.version DESC
)
INSERT INTO plantilla_correo (organizacion_id, codigo, version, asunto, cuerpo, es_activa, creado_en)
SELECT a.organizacion_id,
       a.codigo,
       (SELECT max(t.version) + 1 FROM plantilla_correo t
         WHERE t.organizacion_id = a.organizacion_id AND t.codigo = a.codigo),
       regexp_replace(
           replace(replace(a.asunto, 'Tienes {{plazo}} desde este correo', 'Tienes {{plazo}}'),
                   '{{plazo}} desde este correo', '{{plazo}}'),
           '[^.!?[:space:]][^.!?\n]*desde este correo[^.!?\n]*[.!?]?', 'Tienes {{plazo}}.', 'gi'),
       regexp_replace(
           replace(replace(a.cuerpo, 'Tienes {{plazo}} desde este correo', 'Tienes {{plazo}}'),
                   '{{plazo}} desde este correo', '{{plazo}}'),
           '[^.!?[:space:]][^.!?\n]*desde este correo[^.!?\n]*[.!?]?', 'Tienes {{plazo}}.', 'gi'),
       true,
       now()
  FROM en_alcance a
 WHERE a.cuerpo ILIKE '%desde este correo%' OR a.asunto ILIKE '%desde este correo%';

-- Y se jubilan las activas que todavía lo dicen. Nunca la más nueva de su código: es la que se
-- acaba de publicar, y si la sustitución hubiera dejado algo, apagarla dejaría a la empresa sin
-- ningún texto para el aviso.
UPDATE plantilla_correo pc
   SET es_activa = false
 WHERE pc.es_activa
   AND (pc.cuerpo ILIKE '%desde este correo%' OR pc.asunto ILIKE '%desde este correo%')
   AND (pc.codigo = 'PRUEBA_DISPONIBLE'
        OR EXISTS (SELECT 1
                     FROM plantilla_correo_vacante pcv
                     JOIN vacante v ON v.id = pcv.vacante_id
                    WHERE pcv.aviso_codigo = 'PRUEBA_DISPONIBLE'
                      AND pcv.plantilla_codigo = pc.codigo
                      AND v.organizacion_id = pc.organizacion_id))
   AND pc.version < (SELECT max(t.version) FROM plantilla_correo t
                      WHERE t.organizacion_id = pc.organizacion_id AND t.codigo = pc.codigo);

-- ============================================================================
-- 5 · Los avisos nuevos de la campana
-- ============================================================================
-- Sin tabla nueva: `aviso_portal` guarda el tipo como texto (V56).
COMMENT ON COLUMN aviso_portal.tipo IS
    'Qué clase de noticia es. De la vacante: REMUNERACION_ACTUALIZADA (V54), VACANTE_ACTUALIZADA '
    '(V58), VACANTE_ELIMINADA (V60). De las reseñas (V63): RESENA_PUBLICADA, RESENA_EDITADA, '
    'REPORTE_RESENA_RESUELTO, RESPUESTA_RESENA_OCULTADA. De las etapas (V70), el mismo código que '
    'el correo que la acompaña: PRUEBA_DISPONIBLE, POSTULACION_AVANZA, POSTULACION_NO_CONTINUA, '
    'POSTULACION_CERRADA, RETIRO_CONFIRMADO. Y los recordatorios (V70): RECORDATORIO_EVALUACION y '
    'RECORDATORIO_PRUEBA. El texto de lo que pasó va en titulo y cuerpo.';
